- .gitignore
- ex_schemas/schema_v2.json
- ex_topo/duffy_ex_data.yml
- ex_topo/ex_data.yml
- roles/common/tasks/main.yml
- roles/duffy/tasks/main.yml
- roles/duffy/tasks/provision_res_defs.yml
- roles/duffy/tasks/provision_resource_group.yml
- roles/duffy/tasks/teardown_res_defs.yml
- roles/duffy/tasks/teardown_resource_group.yml
- roles/duffy/vars/duffy_creds.yml
- roles/output_writer/tasks/main.yml
- site.yml
Two commits to accommodate the Duffy provisioner from CentOS CI (https://wiki.centos.org/QaWiki/CI/Duffy).
> Duffy provisioner/teardown tooling

- docs/source/intro.rst
- docs/source/intro_getting_started.rst
Updated the docs with brief directory structure.
> added getting started with directory structure

- roles/aws/tasks/deprovision_s3_res_defs.yml
- roles/aws/tasks/provision_aws_s3.yml
added missing files w.r.to aws_s3
> added missing provisioning/deprovisioning playbooks of aws_s3

- inventory_overlay.example
This is the example overlay file from our discussion today
> example inventory overlay file 

- ex_schemas/schema_v2.json
- roles/aws/tasks/deprovision_aws_ec2_key_res_defs.yml
- roles/aws/tasks/deprovision_resource_group.yml
- roles/aws/tasks/deprovision_s3_res_defs.yml
- roles/aws/tasks/provision_aws_ec2.yml
- roles/aws/tasks/provision_aws_ec2_key.yml
- roles/aws/tasks/provision_aws_s3.yml
- roles/aws/tasks/provision_res_defs.yml
- roles/openstack/tasks/provision_os_keypair.yml
Added aws_ec2_key feature in linchpin .
Fixed keypair generation bug on os_keypair feature.
Changed provsioning design of aws resources.
> design tweaks and feature add on

- README.md
- provision/roles/aws/tasks/deprovision_resource_group.yml
- provision/roles/aws/tasks/provision_resource_group.yml
- provision/roles/duffy/tasks/provision_resource_group.yml
- provision/roles/duffy/tasks/teardown_resource_group.yml
- provision/roles/gcloud/tasks/provision_resource_group.yml
- provision/roles/openstack/tasks/provision_resource_group.yml
updated readme 
fixed references to include vars, w.r.to updated folder structure.
> updated commands in readme and fixed the include_vars references 

- ex_schemas/schema_v2.json
- provision/roles/aws/tasks/deprovision_aws_cfn.yml
- provision/roles/aws/tasks/deprovision_aws_ec2_key_res_defs.yml
- provision/roles/aws/tasks/deprovision_aws_ec2_res_defs.yml
- provision/roles/aws/tasks/deprovision_res_defs.yml
- provision/roles/aws/tasks/deprovision_resource_group.yml
- provision/roles/aws/tasks/main.yml
- provision/roles/aws/tasks/provision_aws_cfn.yml
- provision/roles/aws/tasks/provision_res_defs.yml
- provision/roles/aws/tasks/provision_resource_group.yml
- provision/roles/common/tasks/main.yml
currents commits will able linch-pin to provision cloud formation templates
> added aws_cfn provisioning feature to linch-pin

- linchpin_config.yml
- provision/roles/common/tasks/main.yml
- provision/roles/openstack/tasks/provision_os_keypair.yml
- provision/roles/output_writer/tasks/main.yml
- provision/site.yml
added keystore, outputs folders to capture the keys and topology_output_files linchpin .
paths of these folders can be configured in linchpin_config.yml
> added configurable keystore and outputs folders 

- ex_schemas/schema_v2.json
- provision/roles/openstack/tasks/provision_os_object.yml
- provision/roles/openstack/tasks/provision_os_volume.yml
- provision/roles/openstack/tasks/provision_res_defs.yml
linchpin will be able to provision openstack cinder volumes and swift containers
> added openstack volumes and containers provisioning/deprovisioning feature

- provision/roles/openstack/tasks/main.yml
- provision/roles/openstack/tasks/provision_os_heat.yml
- provision/roles/openstack/tasks/provision_os_object.yml
- provision/roles/openstack/tasks/provision_os_server.yml
- provision/roles/openstack/tasks/provision_os_volume.yml
- provision/roles/output_writer/tasks/main.yml
fixed output formatting of openstack stack resources:
- os_heat
- os_volume
- os_object
> fixed output formatting of openstack stack resources

- provision/roles/openstack/tasks/provision_os_keypair.yml
- provision/roles/openstack/tasks/provision_os_server.yml
- provision/roles/output_writer/tasks/main.yml
fixed output formatting of os_keypair
> fixed output formatting of os_keypair resource type

- linchpin_config.yml
- provision/filter_plugins/duffy_inventory.py
- provision/invfilter.yml
Fixes bug #41
When duffy_res is empty, return empty string
remove duplicate entry in linchpin_config.yml
> Fix bug around empty duffy_res

- library/async_status.py
custom fix for ansible async_status module , until there is community bug fix for os_server module .
> custom module fix for async_status module

- library/async_status.py
- provision/filter_plugins/duffy_inventory.py
- provision/invfilter.yml
- provision/roles/openstack/tasks/provision_os_keypair.yml
- provision/site.yml
Add a new line to strings that might not have them to ensure the inventory prints out properly.
> Update duffy_inventory.py to ensure every line ends properly

- ex_schemas/schema_v2.json
- provision/roles/common/tasks/main.yml
- provision/roles/openstack/tasks/provision_os_object.yml
- provision/roles/output_writer/tasks/main.yml
- provision/roles/output_writer/tasks/update_async_outputs.yml
- provision/roles/output_writer/tasks/update_os_obj_outputs.yml
- provision/roles/output_writer/tasks/update_os_server_outputs.yml
- provision/roles/output_writer/tasks/wait_on_os_obj.yml
- provision/roles/rackspace/handlers/main.yml
- provision/roles/rackspace/tasks/main.yml
- provision/roles/rackspace/tasks/provision_rax_server.yml
- provision/roles/rackspace/tasks/provision_res_defs.yml
- provision/roles/rackspace/tasks/provision_resource_group.yml
- provision/roles/rackspace/vars/ex_rx_creds.yml
- provision/site.yml
added async provisioning for os_object
added feature to provision rackspace server supports only async== false
> added feature to provision rackspace server 

- library/async_status_custom.py
- provision/roles/openstack/tasks/provision_os_heat.yml
- provision/roles/openstack/tasks/provision_os_volume.yml
- provision/roles/output_writer/tasks/main.yml
- provision/roles/output_writer/tasks/update_async_outputs.yml
- provision/roles/output_writer/tasks/update_os_heat_outputs.yml
- provision/roles/output_writer/tasks/update_os_volume_outputs.yml
- provision/roles/output_writer/tasks/wait_on_os_heat.yml
- provision/roles/output_writer/tasks/wait_on_os_server.yml
- provision/roles/output_writer/tasks/wait_on_os_volume.yml
os_volume module raised the same bug which was raised by os_server module ,
Moreover , it can be fixed with the async_status_custom module.
Added Async provisioning  for openstack heat templates 
fixed a bug with async teardown of os_server module
> added async provisioning to os_volume resource

- ex_schemas/schema_v3.json
- library/schema_check.py
- linchpin_config.yml
- provision/invfilter.yml
- provision/roles/aws/tasks/provision_aws_cfn.yml
- provision/roles/aws/tasks/provision_aws_ec2.yml
- provision/roles/aws/tasks/teardown_aws_cfn.yml
- provision/roles/aws/tasks/teardown_aws_ec2.yml
- provision/roles/gcloud/tasks/provision_res_defs.yml
- provision/roles/openstack/tasks/provision_os_heat.yml
- provision/roles/openstack/tasks/provision_os_keypair.yml
- provision/roles/openstack/tasks/provision_os_object.yml
- provision/roles/openstack/tasks/provision_os_server.yml
- provision/roles/openstack/tasks/provision_os_volume.yml
- provision/roles/output_writer/tasks/main.yml
- provision/roles/output_writer/tasks/update_async_outputs.yml
- provision/roles/output_writer/tasks/update_aws_cfn_outputs.yml
- provision/roles/output_writer/tasks/update_gcloud_gce_outputs.yml
- provision/roles/output_writer/tasks/wait_on_aws_cfn.yml
- provision/roles/output_writer/tasks/wait_on_gcloud_gce.yml
added async provisioning to aws_cfn resources 
added missing files of aws_cfn async provisioning
added async provisioning to aws_cfn resources
added missing files of aws_cfn async provisioning
added gcloud_gce async provisioning
added output formatting for gcloud_gce
added schema_v3 for strict resource_grp validations
fixed resource_group_name conflict
> async provisioning of resources and schema_v3 update

- provision/InventoryFilters/AWSInventory.py
- provision/InventoryFilters/GCloudInventory.py
- provision/InventoryFilters/InventoryFilter.py
- provision/InventoryFilters/OpenstackInventory.py
- provision/filter_plugins/aws_inv.py
- provision/filter_plugins/gcloud_inv.py
- provision/filter_plugins/os_inv.py
- provision/roles/inventory_gen/templates/aws_inventory_formatter.j2
- provision/roles/inventory_gen/templates/gcloud_inventory_formatter.j2
- provision/roles/inventory_gen/templates/openstack_inventory_formatter.j2
InventoryFilters package has the abstract/concrete  classes needed for writing the filters. 
updated openstack, aws , gcloud inventory filters to implement object oriented InventoryFilter class.
> implemented InventoryFilters package

- provision/InventoryFilters/OpenstackInventory.py
- provision/roles/gcloud/tasks/provision_gcloud_gce.yml
- provision/roles/gcloud/tasks/provision_res_defs.yml
- provision/roles/inventory_gen/tasks/main.yml
- provision/roles/inventory_gen/templates/openstack_inventory_formatter.j2
- provision/roles/output_writer/tasks/main.yml
- provision/roles/output_writer/tasks/wait.yml
- provision/roles/output_writer/tasks/wait_on_aws_ec2.yml
- provision/roles/output_writer/tasks/wait_on_gcloud_gce.yml
- tests/test_linchpin_env.py
> Bug fixes for async provisioning and inventory generation

- ex_topo/ex_topology_output.yaml
- provision/InventoryFilters/OpenstackInventory.py
- provision/roles/gcloud/tasks/provision_gcloud_gce.yml
- provision/roles/gcloud/tasks/provision_res_defs.yml
- provision/roles/inventory_gen/tasks/main.yml
- provision/roles/inventory_gen/templates/openstack_inventory_formatter.j2
- provision/roles/output_writer/tasks/main.yml
- provision/roles/output_writer/tasks/wait.yml
- provision/roles/output_writer/tasks/wait_on_aws_ec2.yml
- provision/roles/output_writer/tasks/wait_on_gcloud_gce.yml
- tests/test_linchpin_env.py
The example output file had a password in it. We've mitigated the password internally, but just in case this shouldn't be in the outputs. Removing it now.
There are many files listed due to a rebase which needed to happen. These files are essentially unchanged, only the last commit changed files related to this PR.
> Redact passwords from outputs in general. 

- .gitignore
- ex_topo/duffy_3node_inventory_layout.yml
- linchpin_config.yml
- provision/InventoryFilters/AWSInventory.py
- provision/InventoryFilters/DuffyInventory.py
- provision/InventoryFilters/GCloudInventory.py
- provision/InventoryFilters/GenericInventory.py
- provision/InventoryFilters/InventoryFilter.py
- provision/InventoryFilters/InventoryProviders.py
- provision/InventoryFilters/OpenstackInventory.py
- provision/filter_plugins/duffy_inv.py
- provision/invfilter.yml
- provision/roles/inventory_gen/tasks/main.yml
- provision/roles/inventory_gen/templates/duffy_inventory_formatter.j2
- provision/roles/output_writer/tasks/main.yml
DuffyInventory class will replace the duffy_inventory.py filter I wrote as an original POC. This class and its subsequent related classes provide similar functionality, but using the new ABC structure @samvarankashyap created.
> DuffyInventory class to follow InventoryFilters 

- provision/roles/output_writer/tasks/main.yml
> add yaml extension to output from output_writer

- tests/jjb/committed/linch-pin-committed-jobs.yml
- tests/jjb/committed/linch-pin-committed-project-macros.yml
- tests/jjb/committed/linch-pin-defaults.yml
- tests/jjb/linch-pin-defaults.yml
- tests/jjb/pr/linch-pin-defaults.yml
- tests/jjb/pr/linch-pin-pr-jobs.yml
- tests/jjb/pr/linch-pin-pr-project-macros.yml
> Add JJB for PR and committed on linch-pin

- tests/jjb/committed/linch-pin-committed-jobs.yml
- tests/jjb/pr/linch-pin-pr-jobs.yml
- Add place holder for cron on committed jobs
> support conditional publisher with multiple actions

- docs/source/intro_installation.rst
- ex_schemas/schema_v3.json
- ex_topo/ex_os_server_fp.yml
- ex_topo/ex_os_server_fp2.yml
- provision/filter_plugins/os_net.py
- provision/roles/aws/templates/output_formatter.j2
- provision/roles/openstack/tasks/provision_os_server.yml
- provision/roles/output_writer/templates/output_formatter.j2
- requirements.txt
Summary:
- user can provide the floating ip pools using fip_pool attribute in topology.
- schema update to incorporate floating ip pools
- added os_net for translating networks to nics
> Bugfix for floating ip issue #99

- InventoryFilters/BeakerInventory.py
- cli/cli.py
- cli/utils.py
- linchpin.py
- linchpin_api/v1/api.py
- linchpin_api/v1/invoke_playbooks.py
- linchpin_api/v1/utils.py
- provision/roles/output_writer/templates/output_formatter.j2
- requirements.txt
- templates/PinFile.j2
- tests/mockdata/PinFile
- tests/mockdata/inventory_mock.py
- tests/test.py
- tests/test_linchpin_api.py
- tests/test_linchpin_cli.py
- tests/test_linchpin_inventory_filters.py
- tests/test_linchpin_inventory_gen.py
- tests/test_linchpin_invocation.py
Summary: 
- changed name of folder from inventory to inventories generated on linchpin init
- dropped linchpin_config.yml on linchpin init
- removed topology_upstream , layout_upstream attributes in PinFile . However, user can specify either using --upstream while using linchpin topology get or linchpin layout get.
- changed variable names and references of lpf to pf ( pinfile ) for consistency
- updated requirements.txt
> code refactor and bug fixes

- provision/filter_plugins/unicode_filter.py
- provision/roles/output_writer/tasks/main.yml
- provision/roles/output_writer/templates/output_formatter.j2
summary:
- have fixes for _ansible_item_label issue
> Bugfix for ansible2.2.1

- setup.py
Summary:
- Updated metadata in setup.py.
- Requiements.txt is added to setup.py such that its accessible while installing linchpin though PyPi.
> added requirements.txt to linchpin PyPi build

- linchpin_api/v1/api.py
- provision/roles/common/tasks/main.yml
- provision/site.yml
- setup.py
Summary: 
- Updated the config_file paths
- Removed unwanted override of config_file in common role
- Updated and removed debug statements in linchpin_api
> Bugfix: For issue #135 

- InventoryFilters/GenericInventory.py
- InventoryFilters/InventoryFilter.py
- InventoryFilters/LibvirtInventory.py
- InventoryFilters/OpenstackInventory.py
- linchpin_api/v1/invoke_playbooks.py
- provision/filter_plugins/ordered_yaml.py
- provision/invgen.yml
- provision/roles/inventory_gen/tasks/main.yml
- requirements.txt
- setup.py
- tests/jjb/pr/linch-pin-pr-jobs.yml
- tests/linchpin_utils/inventory_utils.py
- tests/test_linchpin_inventory_filters.py
Summary:
- added ordered_yaml filter to parse inventory_layout file
- updated InventoryFilters , inventory_gen role to reflect the changes
- updated requirements.txt
Fixes #153
> Bugfix for Inventory to Host ip mapping 

- CONTRIBUTING.rst
The last three sections of this document went missing, mysteriously on
the last commit. #strangethingsarehappening
> Updating CONTRIBUTING.rst with lost data

- docs/source/config_general.rst
- docs/source/config_layout.rst
- docs/source/linchpincli.rst
- docs/source/topologies.rst
Fix minor problems after went through the doc.
Signed-off-by: Wayne Sun <gsun@redhat.com>
> docs: Minor fixes on the docs

- templates/linchpin_config.yml.j2
`linchpin config --reset` now generates correct schema
> *HOTFIX* Fixes #171 - incorrect schema version

- presentations/lpdemo-0-install
- presentations/lpdemo-4-rise
updated to 0.9.0
fix output of lpdemo-4-rise to show the proper CentOS output
> Updated presentation to 0.9.0, small bugfix

- setup.py
> added python-krbV optional dependency for Beaker

- requirements.txt
> Fixes conflict with requests and openstackclient

- docs/source/topologies.rst
- docs/source/topologies_beaker.rst
Simple documentation updates from the master branch.
> Backport documentation for beaker

- linchpin/api/__init__.py
Fix bug that was returning before finishing a loop on multiple targets
> Allow multiple targets again

- linchpin/provision/roles/common/tasks/main.yml
- linchpin/provision/roles/duffy/tasks/main.yml
- linchpin/provision/roles/duffy/tasks/provision_res_defs.yml
- linchpin/provision/roles/output_writer/tasks/main.yml
> Updated duffy playbooks w.r.to the schema changes to make duffy work

- .gitignore
- .travis.yml
- linchpin/hooks/action_managers/subprocess_action_manager.py
- linchpin/tests/cli/test_context_pass.py
- linchpin/tests/mockdata/contextdata.py
- linchpin/tests/mockdata/dummy/conf/linchpin.conf
Currently, there's coverage for api and context classes in travis. This PR gets us started testing on PRs against the develop branch.
> Add basic travis-ci support 

- docs/source/config.rst
- docs/source/config_ansiblevars.rst
These are the remaining docs from #206, ReST-ified.
closes #230
> Document ansible config & extra vars

- linchpin/__init__.py
> Removed -cp from click option fixes #251

- linchpin/api/__init__.py
> Bugfix: added self to ctx object fixes issue #253

- README.rst
- docs/source/installation.rst
- docs/source/intro.rst
- docs/source/roadmap/ROADMAP_1_1.rst
- linchpin/version.py
- scripts/create_pypi_package.sh
See [v1.0.0 RELEASE NOTES](https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/docs/source/release/RELEASE_1_0_0.rst) for detail on what all went in to this release.
WHEW!
> HERE IT IS - Release v1.0.0!!!

- linchpin/provision/roles/libvirt/tasks/main.yml
- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
- linchpin/provision/roles/libvirt/tasks/provision_res_defs.yml
- linchpin/provision/roles/libvirt/tasks/teardown_libvirt_node.yml
- linchpin/provision/roles/libvirt/templates/libvirt_node.xml.j2
> Fix qemu kvm path

- docs/source/release/RELEASE_1_0_1.rst
- linchpin/__init__.py
- linchpin/api/__init__.py
- linchpin/api/context.py
- linchpin/defaults/schemas/schema_v4.json
- linchpin/linchpin.conf
- linchpin/provision/InventoryFilters/GenericInventory.py
- linchpin/provision/InventoryFilters/OpenstackInventory.py
- linchpin/provision/library/auth_driver.py
- linchpin/provision/roles/aws/tasks/provision_resource_group.yml
- linchpin/provision/roles/aws/tasks/teardown_resource_group.yml
- linchpin/provision/roles/common/tasks/load_evars_from_ini.yml
- linchpin/provision/roles/gcloud/tasks/provision_gcloud_gce.yml
- linchpin/provision/roles/gcloud/tasks/provision_resource_group.yml
- linchpin/provision/roles/gcloud/vars/ex_gcloud_creds.yml
- linchpin/provision/roles/inventory_gen/tasks/main.yml
- linchpin/provision/roles/openstack/tasks/main.yml
- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
- linchpin/provision/roles/openstack/tasks/provision_resource_group.yml
- linchpin/provision/roles/output_writer/tasks/main.yml
- linchpin/provision/roles/output_writer/tasks/update_os_server_outputs.yml
- linchpin/version.py
- requirements.txt
- scripts/create_pypi_package.sh
This is the commits for the bugfix update to v1.0.1. Some of the commits below have already been approved in a previous PR, sometimes rebasing causes this issue. Please verify your use cases and comment if needed.
> Release for bugfix update (1.0.1)

- CONTRIBUTING.rst
- docs/source/libapi.rst
- docs/source/libbase.rst
- docs/source/libcli.rst
- docs/source/release/RELEASE_1_0_1.rst
- linchpin/api/__init__.py
- linchpin/api/context.py
- linchpin/cli/context.py
Adding more documentation never hurts, right? 
This update focuses on improving the Python API docs a bit more. The CONTRIBUTING.rst document is also updated to explain our workflow better, and accommodate the new linchpin naming.
> More documentation updates

- linchpin/defaults/schemas/schema_v3.json
- linchpin/defaults/schemas/schema_v4.json
- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
Add support for cloud-init's userdata argument to OpenStack
provisioning
> Add userdata support to OpenStack

- linchpin/__init__.py
- linchpin/api/__init__.py
- linchpin/api/callbacks.py
- linchpin/api/context.py
- linchpin/api/github.py
- linchpin/hooks/__init__.py
- linchpin/hooks/action_managers/action_manager.py
- linchpin/hooks/action_managers/ansible_action_manager.py
- linchpin/hooks/action_managers/subprocess_action_manager.py
- linchpin/provision/InventoryFilters/BeakerInventory.py
- linchpin/provision/InventoryFilters/DuffyInventory.py
- linchpin/provision/InventoryFilters/DummyInventory.py
- linchpin/provision/library/auth_driver.py
landscape.io has some recommendations for improvements, efficiency and style. Fixing them up based upon https://landscape.io/github/CentOS-PaaS-SIG/linchpin/36. 
Additionally, minor changes were made to hooks, which need some manual testing before this PR can be approved. Specifically, ansible and subprocess hooks need to be retested.
> Recommended fixes from landscape.io

- linchpin/api/__init__.py
- linchpin/provision/roles/beaker/tasks/main.yml
- linchpin/provision/roles/dummy/tasks/main.yml
- linchpin/provision/roles/inventory_gen/tasks/main.yml
Fixes #294 
@robled can you test this to verify it works for you?
> remove .yaml from output resources files

- scripts/install_libvirt_deps.sh
Small fix to make libvirt easier to setup.
> installing deps requires -y flag

- linchpin/version.py
- scripts/create_pypi_package.sh
Updated version.py to 1.0.2
Fixed up the create package script to fit the new pypi.org api.
> Updating to BugFix Release 1.0.2

- .gitignore
* Pycharm (.idea)
* Eclipse with pydev (.pydevproject)
> ignore files created by IDEs

- README.rst
> README.rst with correct link to installation

- linchpin/provision/library/os_server2.py
> Fixes Issue #335 openstack multiple provision failure :)

- requirements.txt
This seems to work in my initial testing.
> Move ansible to >=2.3.1 in requirements.txt

- docs/source/topologies_openstack.rst
Add example clouds.yaml and topology file.
Signed-off-by: Niranjan M.R <mrniranjan@redhat.com>
> Add example to provision single system using openstack

- docs/source/config_layout.rst
Signed-off-by: bbhavsar <bbhavsar@redhat.com>
> Minor fix: Frontend has two webhosts as per layout mentioned

- linchpin/defaults/schemas/schema_v4.json
- linchpin/provision/InventoryFilters/InventoryFilter.py
- linchpin/provision/roles/gcloud/tasks/provision_gcloud_gce.yml
> Add support to tags attribute in gcloud_gce provisioning

- .travis.yml
- linchpin/api/__init__.py
- linchpin/api/ansible_runner.py
- linchpin/hooks/action_managers/ansible_action_manager.py
Summary:
1. Added ansible_runner handling both ansible version > 2.4.x & <2.4.x
2. Replaced builtin implementation with ansible runner implementation from linchpin.api
3. Restructured the imports, added ansible runner implementation for ansible2.4
fixes #367
> fixes #364 : Ansible_runner 

- CONTRIBUTING.rst
- docs/source/installation.rst
> Add Testing section to CONTRIBUTING doc

- linchpin/provision/library/openshift.py
> bugfix: Resolved syntax error in openshift.py

- linchpin/api/ansible_runner.py
Ansible does not recognize the packages which are installed in virtualenv
The following fix makes ansible to recognize venv interpreter and packages
> Making ansible honor the virtualenv

- .gitignore
- Dockerfiles/Makefile
- Dockerfiles/centos6/Dockerfile
- Dockerfiles/centos6/start_libvirtd.sh
- Dockerfiles/centos7/Dockerfile
- Dockerfiles/fedora25/Dockerfile
- Dockerfiles/fedora26/Dockerfile
- Dockerfiles/gen_pip_install.sh
- Dockerfiles/linchpin-install.sh
- Dockerfiles/linchpin-test.sh
- Dockerfiles/run_tests.sh
- requirements.txt
First attempt at docker images to verify linchpin works on
centos and fedora environments.  Currently it only tests libvirt
and dummy.
> Docker images for testing.

- docs/source/installation.rst
Update generic installation notes
Added sub-section for installing on Fedora 26
Added sub-section for installing on RHEL 7.4
> Update installation doc and add OS sub-sections

- Dockerfiles/Makefile
- Dockerfiles/linchpin-test.sh
- Dockerfiles/run_tests.sh
Add in duffy but conditionally if duffy.key exists.
linchpin down was missing
> Change order from newest distros to oldest.

- linchpin/__init__.py
- linchpin/api/__init__.py
- linchpin/provision/filter_plugins/duffy_inventory.py
- linchpin/provision/roles/duffy/tasks/main.yml
- linchpin/rundb/tinyrundb.py
- linchpin/tests/api/test_init_pass.py
Fixes #397 #389 #388 
Changes the default count for linchpin journal to 3, as that makes logical sense.
> Misc fixes

- .gitignore
- Dockerfiles/linchpin-install.sh
- Dockerfiles/run_tests.sh
now pulls in the ansible-duffy module and places the duffy.key in the containers homedir.
> Fixes to run duffy

- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
> Bugfix: updated URI for Provisioning when cloudconfig is not defined

- linchpin/provision/roles/libvirt/tasks/provision_libvirt_network.yml
- linchpin/provision/roles/libvirt/templates/libvirt_network.xml.j2
$Subject
Added bridge parameter to network and defaulted it to virbr0
> Added bridge parameter to libvirt_network provisioning

- linchpin/api/__init__.py
- linchpin/provision/library/rundb.py
- linchpin/provision/roles/common/tasks/initialize_rundb.yml
- linchpin/provision/roles/libvirt/tasks/teardown_libvirt_node.yml
> Use os.makedirs instead of os.mkdir

- Dockerfiles/centos6/Dockerfile
- Dockerfiles/centos7/Dockerfile
- Dockerfiles/fedora25/Dockerfile
- Dockerfiles/fedora26/Dockerfile
- Dockerfiles/fedora27/Dockerfile
- Dockerfiles/linchpin-test.sh
- linchpin/provision/roles/libvirt/tasks/copy_image_src_local.yml
> Add dependencies to make libvirt provisioning work.

- linchpin/provision/roles/libvirt/templates/libvirt_network.xml.j2
> bugfix: added missing quotes in network attribute

- linchpin/version.py
The following were updated/fixed in this release:
* Bugfix: Added missing quotes in network attribute
* Bugfix: Make the 'delete associated images' part actually work
* Added bridge parameter to libvirt_network provisioning
* Add dependencies to make libvirt provisioning work (testing)
* Bugfix: Fix #411 using os.makedirs instead of os.mkdir
* allow ansible-playbook to destroy using rundb
* Bugfix: updated URI for Provisioning when cloudconfig is not defined
> Version 1.2.1 updates

- linchpin/version.py
Updated version to a normalized version for pypi. This is the release candidate 1 (rc1)
> Release v1.5.0rc1

- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
wait up to 5 minutes for guest network to come up.
> Fix libvirt to not wait forever for ip address

- .travis.yml
- linchpin/api/ansible_runner.py
- linchpin/provision/roles/dummy/tasks/provision_res_defs.yml
- linchpin/provision/roles/dummy/tasks/teardown_res_defs.yml
- linchpin/tests/api/test_init_pass.py
- requirements.txt
Provides several fixes which are minor but needed. The commit messages should be clear enough to explain.
> Miscellaneous minor fixes

- docs/source/aws.rst
- docs/source/beaker.rst
- docs/source/developer_info.rst
- docs/source/duffy.rst
- docs/source/examples/workspace/PinFile.complex.yml
- docs/source/examples/workspace/topologies/libvirt-el7net.yml
- docs/source/gcloud.rst
- docs/source/libbase.rst
- docs/source/libcli.rst
- docs/source/libdocs.rst
- docs/source/libextras.rst
- docs/source/libhooks.rst
- docs/source/libshell.rst
- docs/source/libvirt.rst
- docs/source/openshift.rst
- docs/source/openstack.rst
- docs/source/ovirt.rst
- docs/source/providers.rst
- linchpin/__init__.py
- linchpin/hooks/__init__.py
- linchpin/provision/roles/libvirt/files/schema.json
- scripts/install_selinux_venv.sh
Reworked API docs and did a minor clean up of certain python libs so the docs come in cleaner.
> API Documentation, minor cleanup

- docs/source/conf.py
- docs/source/configuration.rst
- linchpin/version.py
Change docs links to point to develop instead of herlo repository. Other minor changes.
> Update version to 1.5.0

- docs/source/aws.rst
- linchpin/provision/roles/aws/tasks/provision_aws_ec2.yml
- linchpin/version.py
* Update version.py to 1.5.1
* Fix some minor aws docs 
* Make the AWS keypair optional
> Update to v1.5.1

- config/Dockerfiles/Jenkinsfile
- config/Dockerfiles/JenkinsfileStageMerge
- config/Dockerfiles/JenkinsfileStageTrigger
- config/s2i/create-containers.sh
Fixed the TAGS used for containers.
Changed DOCKER_REPO_URL to use a global default if defined. (makes devel env easier)
> Add stage/merge job which will rebuild containers needed to test.

- config/Dockerfiles/Jenkinsfile
- config/Dockerfiles/fedora26/Dockerfile
- config/Dockerfiles/fedora27/Dockerfile
- config/Dockerfiles/init_libvirt.sh
Systemd is not happy in nested virt environment.
> Enable libvirt to work on centos7 and fedora2[67].

- config/Dockerfiles/Jenkinsfile
- config/Dockerfiles/centos6/Dockerfile
- config/Dockerfiles/centos7/Dockerfile
- config/Dockerfiles/fedora26/Dockerfile
- config/Dockerfiles/fedora27/Dockerfile
- config/Dockerfiles/linchpin-install.sh
- config/Dockerfiles/linchpin-tests.sh
> Make duffy key and module available to containers

- config/s2i/jenkins/master/configuration/jobs/ci-pipeline-linchpin-merge/config.xml
- config/s2i/jenkins/master/configuration/jobs/ci-pipeline-linchpin-trigger/config.xml
- config/s2i/jenkins/master/configuration/jobs/ci-pipeline-linchpin/config.xml
Include ci-pipeline-linchpin, ci-pipeline-linchpin-trigger and
ci-pipeline-linchpin-merge.
Future feature:
Put these as templates in dev_setup and allow variables to
define a person fork of the repo which would change it from
upstream.
> Upstream jobs

- docs/source/examples/workspace/topologies/dummy.yml
- docs/source/includes/journal_target.rst
- docs/source/includes/journal_tx.rst
- docs/source/linchpin_journal.rst
- linchpin/__init__.py
- linchpin/callbacks.py
- linchpin/shell/__init__.py
Fixes #501 and begins prep for #499
> Transactions in linchpin journal

- docs/source/includes/cli_help.rst
- linchpin/shell/__init__.py
Help messages for pinfile-output and template data were swapped.
Signed-off-by: Lukas Bednar <lbednar@redhat.com.com>
> CLI options: fix help message for pinfile-output and template-data

- config/Dockerfiles/Jenkinsfile
- config/README.rst
- config/s2i/create-containers.sh
- config/s2i/jenkins/jenkins-persistent-buildconfig-template.yaml
- config/s2i/jenkins/master/configuration/init.groovy
- config/s2i/jenkins/master/configuration/scriptApproval.xml
Some re-working to make it easier to support credentials and to make it easier to override which drivers are tested from a particular server.
> Downstream jobs

- .gitignore
- config/Dockerfiles/Jenkinsfile
- config/Dockerfiles/linchpin-tests.sh
- config/Dockerfiles/run_tests.sh
- docs/source/examples/workspace/topologies/aws-ec2-new.yml
> Enable testing of aws-ec2-new driver.

- config/Dockerfiles/centos6/Dockerfile
- config/Dockerfiles/centos7/Dockerfile
- config/Dockerfiles/fedora26/Dockerfile
- config/Dockerfiles/fedora27/Dockerfile
- config/Dockerfiles/linchpin-tests.sh
- config/Dockerfiles/run_tests.sh
Tested locally with a bkr-new.tgz file in
keys/bkr-new which contains the following files:
bkr-new.keytab
client.conf
install.sh
RedHatInternalCA.pem
> Final pieces to make beaker testing possible

- config/Dockerfiles/Jenkinsfile
Make it possible to enable the beaker driver for testing. :-)
> Actually enable the beaker driver.

- config/s2i/jenkins/master/configuration/jobs/ci-linchpin-GHPRB-merge/config.xml
- config/s2i/jenkins/master/configuration/jobs/ci-linchpin-GHPRB-trigger/config.xml
- config/s2i/jenkins/master/configuration/jobs/ci-linchpin-container/config.xml
- config/s2i/jenkins/master/configuration/jobs/ci-linchpin-merge/config.xml
- config/s2i/jenkins/master/configuration/jobs/ci-linchpin-messageBus-merge/config.xml
- config/s2i/jenkins/master/configuration/jobs/ci-linchpin-messageBus-trigger/config.xml
- config/s2i/jenkins/master/configuration/jobs/ci-linchpin/config.xml
GitHubPullRequestBuilder triggers are active
MessageBus triggers are deactivated.
> Default jobs for running linchpin.

- docs/source/examples/workspace/Bad-Data.libvirt-mi.yml
- linchpin/cli/__init__.py
- linchpin/shell/__init__.py
- linchpin/tests/test_init_pass.py
- linchpin/utils/dataparser.py
- requirements.txt
> Fix TypeError when missing a template

- docs/source/examples/workspace/topologies/aws-ec2-new.yml
- linchpin/provision/roles/aws/files/schema.json
- linchpin/provision/roles/aws/tasks/provision_aws_ec2.yml
- requirements.txt
> Add support for passing instance_tags for aws driver.

- config/Dockerfiles/Jenkinsfile
- config/Dockerfiles/JenkinsfileContainer
- config/Dockerfiles/JenkinsfileGHPRTrigger
- config/Dockerfiles/JenkinsfileMessageBusTrigger
- config/Dockerfiles/linchpin-test.sh
- config/Dockerfiles/linchpin-tests.sh
- config/Dockerfiles/run_tests.sh
- config/README.rst
- config/s2i/jenkins/jenkins-continuous-infra-slave-buildconfig-template.yaml
- config/s2i/jenkins/jenkins-persistent-buildconfig-template.yaml
- src/org/centos/pipeline/LinchpinPipelineUtils.groovy
- vars/linchpinPipelineUtils.groovy
Also rename target to distro and drivers to target.
> Test specific targets based on the Changed files in the PR.

- config/Dockerfiles/Jenkinsfile
- config/Dockerfiles/run_tests.sh
- docs/source/examples/workspace/topologies/os-server-new.yml
- docs/source/examples/workspace/topologies/os-vol-new.yml
Add openstack tests for provisioning compute instances, cinder volumes, and security groups
> Add openstack tests

- config/Dockerfiles/Jenkinsfile
- config/Dockerfiles/JenkinsfileContainer
- linchpin/provision/openstack.yml
Add files which, when changed, cause Jenkins to run Openstack tests
> Add openstack test triggers

- linchpin/__init__.py
- linchpin/cli/__init__.py
- linchpin/provision/roles/aws/tasks/teardown_aws_ec2.yml
- linchpin/provision/roles/aws/tasks/teardown_resource_group.yml
- linchpin/utils/dataparser.py
- linchpin/version.py
- scripts/install_libvirt_deps.sh
Fixes #488 - * removed errant if/else which was providing incorrect return code output to the user
* Add no_log in a few places which would display sensitive data
* Moved the code for distilling data into a distill_data method
> Fixup reporting issues, other minor fixes

- linchpin/cli/__init__.py
> Fix linchpin distiller to render values of every server provisioned

- linchpin/cli/__init__.py
Fixes AWS instance render to resources file.
> bugfix: fix distiller render for aws instances

- linchpin/provision/roles/libvirt/tasks/copy_image_src.yml
- linchpin/provision/roles/libvirt/tasks/copy_image_src_local.yml
- linchpin/provision/roles/libvirt/tasks/copy_image_src_remote.yml
- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
Fixes: #579
Signed-off-by: Lukas Bednar <lbednar@redhat.com>
> libvirt: expand tilde character from libvirt_image_path

- linchpin/version.py
First time doing this..  let me know if I need to do anything else..  but this should kick off the full testing.
> Update version for 1.5.4

- docs/source/community.rst
- docs/source/conf.py
- docs/source/developer_info.rst
- docs/source/gs/pinfile.rst
- docs/source/includes/footer.rst
- docs/source/includes/pinfile.rst
- docs/source/index.rst
- docs/source/intro_config.rst
Fixes #590 
Fixes #591 
Fixes #595
> Minor docs fixes

- config/Dockerfiles/tests.d/combined/01_beaker_openstack
- docs/source/examples/workspace/PinFile.beaker-openstack.yml
- linchpin/__init__.py
- linchpin/provision/roles/beaker/files/schema.json
- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
During the run of _invoke_playbooks, the resources were set to all resources, but only the current resource is needed. This one line adjustment removes these failures.
> Run one resource at a time

- config/Dockerfiles/Jenkinsfile
- config/Dockerfiles/linchpin-install.sh
- config/Dockerfiles/linchpin-tests.sh
- config/Dockerfiles/tests.d/combined/01_beaker_openstack
- config/Dockerfiles/tests.d/inventory/01_template_inventory
> Rework Credentials 

- docs/source/index.rst
This updates index.rst to use the release value and points to release notes.
> Minor documentation update

- linchpin/provision/library/bkr_info.py
- linchpin/provision/library/bkr_server.py
- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
> WIP - Need to dig a little deeper and see if we need two methods still

- linchpin/provision/roles/aws/tasks/provision_aws_cfn.yml
- linchpin/provision/roles/aws/tasks/provision_aws_ec2.yml
- linchpin/provision/roles/aws/tasks/provision_aws_sg.yml
- linchpin/provision/roles/aws/tasks/provision_resource_group.yml
- linchpin/provision/roles/aws/tasks/teardown_aws_ec2_key.yml
- linchpin/provision/roles/aws/tasks/teardown_aws_s3.yml
- linchpin/provision/roles/gcloud/tasks/provision_gcloud_gce.yml
- linchpin/provision/roles/openstack/tasks/provision_os_heat.yml
- linchpin/provision/roles/openstack/tasks/provision_os_keypair.yml
- linchpin/provision/roles/openstack/tasks/provision_os_object.yml
- linchpin/provision/roles/openstack/tasks/provision_os_server-auto_ip.yml
- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
- linchpin/provision/roles/openstack/tasks/provision_os_sg.yml
- linchpin/provision/roles/openstack/tasks/provision_os_volume.yml
- linchpin/provision/roles/rackspace/tasks/provision_rax_server.yml
Added no_log to some additional tasks.  Should fix anything left over from #511
> add no_log to ansible tasks that may leak secret keys

- linchpin/__init__.py
- linchpin/cli/__init__.py
Moved postup state to cli to make sure post provision hooks occur after the inventory generation
fixes #652
> hook task(s) now execute after inventory generation

- linchpin/InventoryFilters/GenericInventory.py
> Fixes Incorrect inventory populated

- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
sk and I found this while working on on #596 
Fixes #596
> add auto_ip back to os_server provisioning

- linchpin/InventoryFilters/CFGInventoryFormatter.py
- linchpin/InventoryFilters/GenericInventory.py
- linchpin/InventoryFilters/InventoryProviders.py
- linchpin/__init__.py
- linchpin/cli/__init__.py
> Replaced config dicts with ordered dicts for consistent inventory generation

- docs/source/examples/workspace/linchpin.conf
- linchpin/linchpin.constants
- linchpin/provision/roles/aws/tasks/provision_aws_cfn.yml
- linchpin/provision/roles/aws/tasks/provision_aws_ec2.yml
- linchpin/provision/roles/aws/tasks/provision_aws_ec2_key.yml
- linchpin/provision/roles/aws/tasks/provision_aws_sg.yml
- linchpin/provision/roles/aws/tasks/provision_resource_group.yml
- linchpin/provision/roles/aws/tasks/teardown_aws_ec2.yml
- linchpin/provision/roles/aws/tasks/teardown_aws_ec2_key.yml
- linchpin/provision/roles/aws/tasks/teardown_aws_s3.yml
- linchpin/provision/roles/aws/tasks/teardown_resource_group.yml
- linchpin/provision/roles/common/tasks/main.yml
- linchpin/provision/roles/gcloud/tasks/provision_gcloud_gce.yml
- linchpin/provision/roles/gcloud/tasks/provision_resource_group.yml
- linchpin/provision/roles/openshift/tasks/openshift_api_call.yml
- linchpin/provision/roles/openstack/tasks/provision_os_heat.yml
- linchpin/provision/roles/openstack/tasks/provision_os_keypair.yml
- linchpin/provision/roles/openstack/tasks/provision_os_object.yml
- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
- linchpin/provision/roles/openstack/tasks/provision_os_sg.yml
- linchpin/provision/roles/openstack/tasks/provision_os_volume.yml
- linchpin/provision/roles/openstack/tasks/provision_resource_group.yml
- linchpin/provision/roles/ovirt/tasks/provision_resource_group.yml
- linchpin/provision/roles/rackspace/tasks/provision_rax_server.yml
- linchpin/provision/roles/rackspace/tasks/provision_resource_group.yml
Allows users to disable no_log in order to view debugging info at the expense of leaking secret keys
> Add debug mode

- config/Dockerfiles/tests.d/libvirt/02_libvirt-storage
- config/README.rst
- docs/source/examples/workspace/PinFile.libvirt.yml
- docs/source/examples/workspace/topologies/libvirt-storage.yml
- linchpin/provision/roles/libvirt/files/schema.json
- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
- linchpin/provision/roles/libvirt/templates/libvirt_node.xml.j2
> Add ability to provision additional disks for libvirt

- linchpin/utils/dataparser.py
implement un-ordered rendering in hooks to avoid parsing errors
fixes #659
> Parsing JSON for a hook with extra_vars fix

- linchpin/__init__.py
- linchpin/exceptions/__init__.py
- linchpin/shell/__init__.py
> Adjust validation so that 'type' does not create an error

- linchpin/version.py
> Update to v1.6.2

- linchpin/cli/__init__.py
> Fix small regression when creating random new dir

- requirements.txt
> Updated jinja2 minimum requirements to resolve regression in older operating systems

- config/Dockerfiles/tests.d/dummy/03_dummy-hook-flags
- docs/source/examples/workspace/linchpin.conf
- docs/source/examples/workspaces/dummy-hook-flags/PinFile
- docs/source/examples/workspaces/dummy-hook-flags/hooks/ansible/fail_hook/fail_hook.yaml
- docs/source/examples/workspaces/dummy-hook-flags/hooks/ansible/fail_hook/test_net_ping.yml
- docs/source/examples/workspaces/dummy-hook-flags/hooks/ansible/osoos/git_clone.yaml
- docs/source/examples/workspaces/dummy-hook-flags/hooks/ansible/osoos/install_packages.yaml
- docs/source/examples/workspaces/dummy-hook-flags/hooks/ansible/success_hook/success_hook.yaml
- docs/source/examples/workspaces/dummy-hook-flags/layouts/dummy-layout.yml
- docs/source/examples/workspaces/dummy-hook-flags/linchpin.conf
- docs/source/examples/workspaces/dummy-hook-flags/localhost
- docs/source/examples/workspaces/dummy-hook-flags/topologies/dummy-topology.yml
- linchpin/__init__.py
- linchpin/cli/__init__.py
- linchpin/hooks/__init__.py
- linchpin/linchpin.constants
- linchpin/shell/__init__.py
$subject 
--no-hooks ==> skips running hooks 
--run-hooks-on-failure ==> continues with hooks run even one fails . By default its false from linchpin.conf
usage:
```
linchpin -vvvv --creds-path ./credentials/ up --no-hooks
linchpin -vvvv --creds-path ./credentials/ destroy --no-hooks
linchpin -vvvv --creds-path ./credentials/ up --run-hooks-on-failure
linchpin -vvvv --creds-path ./credentials/ destroy --run-hooks-on-failure
```
Example: Workspace : https://github.com/samvarankashyap/linchpin_hooks_openstack_ws
> added --no-hooks and --ignore-failed-hooks flags to commandline

- linchpin/cli/__init__.py
> Updated pinfile path to use workspace when mentioned

- linchpin/shell/__init__.py
> updated inventory_format flag to --if

- docs/source/examples/workspaces/libvirt/PinFile
- docs/source/includes/validate.rst
- linchpin/__init__.py
- linchpin/provision/layout.yml
- linchpin/provision/roles/common/files/schema.json
Causes layouts to be validated when `linchpin up` is run.  As of now, layouts cannot be validated with `linchpin validate`, but I can add that to this PR if #647 is merged first, otherwise I'll submit a separate PR once that is merged
> Add ability to validate layouts

- linchpin/shell/__init__.py
> Update flags ordering and add metavars

- linchpin/provision/roles/dummy/tasks/provision_resource_group.yml
$subject
The above causes regression in integration tests
> Remove duplicate task in dummy provider

- config/Dockerfiles/JenkinsfileBuilder
- config/Dockerfiles/JenkinsfileContainerBuild
- config/Dockerfiles/Makefile
- config/Dockerfiles/linchpin/Dockerfile
- config/Dockerfiles/linchpin/Makefile
- config/Dockerfiles/linchpin/bin/run-linchpin
- config/Dockerfiles/linchpin/test/run
- config/s2i/create-containers.sh
- config/s2i/jenkins/buildah-buildconfig-template.yaml
- config/s2i/jenkins/buildah/Dockerfile
- docs/source/examples/workspaces/dummy/PinFile
Continuous Delivery of the LinchPin Container. Depends on Jenkins multibranch pipelines with both branches and tags.
If a new change is made to the particular branch, develop in our case, a job will launch and build and test a container. If successful, it will be tagged 'latest'. If a tag is added to the branch, a job will launch and build the container also, upon success this will tag 'latest' and the version associated with the tag. (eg. v1.6.3 will get tagged '1.6.3'). In this way, there will be a 'development' container called 'latest', and regular release containers with proper versions.
> Linchpin container release process - rework

- linchpin/InventoryFilters/AWSInventory.py
- linchpin/InventoryFilters/BeakerInventory.py
- linchpin/InventoryFilters/CFGInventoryFormatter.py
- linchpin/InventoryFilters/DuffyInventory.py
- linchpin/InventoryFilters/DummyInventory.py
- linchpin/InventoryFilters/GCloudInventory.py
- linchpin/InventoryFilters/GenericInventory.py
- linchpin/InventoryFilters/InventoryProviders.py
- linchpin/InventoryFilters/JSONInventoryFormatter.py
- linchpin/InventoryFilters/LibvirtInventory.py
- linchpin/InventoryFilters/OpenstackInventory.py
- linchpin/InventoryFilters/OvirtInventory.py
- linchpin/ansible_runner.py
- linchpin/hooks/action_managers/__init__.py
- linchpin/hooks/action_managers/nodejs_action_manager.py
- linchpin/hooks/action_managers/python_action_manager.py
- linchpin/hooks/action_managers/ruby_action_manager.py
- linchpin/hooks/action_managers/subprocess_action_manager.py
- linchpin/provision/library/async_status_custom.py
- linchpin/rundb/tinyrundb.py
Some of the code was not compatible with python 3.  Most of this was just updating import paths
Fixes #701
> Make docs build in python3

- requirements.txt
> Updated configparser version from ancient to 3.5

- linchpin/cli/__init__.py
- linchpin/provision/library/dummy.py
- playbooks/tests/unit_tests.yml
I originally included this in #732 but it appears its also causing #703 to fail (and potentially others) so I thought it would be wise to split it out
> Adjust code style to reflect new flake8 rules

- docs/source/examples/workspaces/openstack/linchpin.conf
- linchpin/version.py
Update to v1.6.4 more data to come.
> Updating to release v1.6.4

- linchpin/provision/roles/openshift/tasks/provision_resource_group.yml
> default to 'default' credprofile when profile not mentioned

- linchpin/__init__.py
- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
> Fail faster when resource provisioning fails + switch off ignore errors in beaker

- docs/source/examples/workspaces/openshift-on-beaker/Makefile
- docs/source/examples/workspaces/openshift-on-beaker/PinFile
- docs/source/examples/workspaces/openshift-on-beaker/README.rst
- docs/source/examples/workspaces/openshift-on-beaker/hooks/ansible/openshift-install-rpmrepo/install_openshift_repo.yml
- docs/source/examples/workspaces/openshift-on-beaker/layouts/openshift.yml
- docs/source/examples/workspaces/openshift-on-beaker/topologies/openshift-on-beaker.yml
- docs/source/examples/workspaces/openshift-on-openstack/Makefile
- docs/source/examples/workspaces/openshift-on-openstack/PinFile
- docs/source/examples/workspaces/openshift-on-openstack/README.rst
- docs/source/examples/workspaces/openshift-on-openstack/hooks/ansible
- docs/source/examples/workspaces/openshift-on-openstack/layouts/openshift.yml
- docs/source/examples/workspaces/openshift-on-openstack/topologies/openshift-on-openstack.yml
Looking for feedback on how I should structure the README.rst.
I would also like to add a make libvirt example as well which would be fully self contained.
> Openshift examples for provisioning in openstack and beaker.

- docs/source/libvirt.rst
> Add documentation to libvirt provider on how to run linchpin as non-root

- config/Dockerfiles/linchpin-tests.sh
- linchpin/version.py
> Pre release linchpin 1.6.5

- linchpin/provision/roles/aws/files/schema.json
- linchpin/provision/roles/aws/tasks/provision_aws_ec2.yml
Add wait_timeout parameter aws resource_def to increase timeout period for tests.
Further, change the default value to 600 instead of 300
ref : https://docs.ansible.com/ansible/2.6/modules/ec2_module.html
> Added wait timeout parameter to aws_ec2 module

- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
- linchpin/version.py
> Update linchpin version to 1.6.5.rc1 to match version in release test

- config/Dockerfiles/JenkinsfileGHPRMerge
> Don't do automatic releases for now

- linchpin/version.py
- requirements.txt
> Release 1.6.5rc2

- linchpin/version.py
> Release 1.6.5

- docs/source/examples/workspaces/aws/PinFile
- docs/source/examples/workspaces/openshift/PinFile
- docs/source/examples/workspaces/openstack/PinFile
To allow easy downstream testing by other teams of upstream examples
> more variables in examples

- linchpin/__init__.py
> Fail on provider playbook failure while provisioning

- config/Dockerfiles/JenkinsfileGHPRMerge
This library gives us the merge commit so we can pass that
to the next job.
> use gitHubAPI to do the merge

- config/Dockerfiles/JenkinsfileGHPRMerge
Reverts CentOS-PaaS-SIG/linchpin#834
> Revert "use gitHubAPI to do the merge"

- docs/source/advanced/cfgs.rst
- docs/source/advanced_topics.rst
- docs/source/outputs/aws.rst
- docs/source/outputs/dummy.rst
- docs/source/outputs/libvirt.rst
- docs/source/outputs/openstack.rst
> Document PinFile configs

- config/Dockerfiles/linchpin/Dockerfile
> Adjust version in Dockerfile

- config/Dockerfiles/tests.d/openstack/06_os-network
- docs/source/examples/workspaces/openstack/PinFile
- docs/source/examples/workspaces/openstack/topologies/os-network.yml
- docs/source/openstack.rst
- linchpin/provision/roles/gather_resources/tasks/main.yml
- linchpin/provision/roles/openstack/files/schema.json
- linchpin/provision/roles/openstack/tasks/main.yml
- linchpin/provision/roles/openstack/tasks/provision_os_network.yml
Summary:
- Updated examples and documentation for os_network role
- Added test for os_network
- Updated playbooks to support os_network ansible module
- Updated schema to support os_network module
fixes #818
> Add support for os_network module

- config/Dockerfiles/JenkinsfileGHPRMerge
Now that we have the merge commit we can enable the release workflow.
> Enable auto release workflow

- linchpin/provision/roles/openstack/tasks/provision_os_network.yml
- linchpin/provision/roles/openstack/tasks/provision_os_router.yml
- linchpin/provision/roles/openstack/tasks/provision_res_defs.yml
> Deduplicate code using set_fact in os_resources

- LICENSE
> Update author and copyright in license

- linchpin/provision/roles/openstack/files/schema.json
Enable unique attribute for all resources types in openstack
> Enable unique attribute for all resource roles

- docs/source/openstack.rst
> nit: fix documentation formatting in openstack docs

- config/Dockerfiles/tests.d/dummy/06-dummy-shell-hooks
- docs/source/examples/workspaces/dummy-shell-hooks/PinFile
- docs/source/examples/workspaces/dummy-shell-hooks/hooks/ansible/fail_hook/fail_hook.yaml
- docs/source/examples/workspaces/dummy-shell-hooks/hooks/ansible/fail_hook/test_net_ping.yml
- docs/source/examples/workspaces/dummy-shell-hooks/hooks/ansible/osoos/git_clone.yaml
- docs/source/examples/workspaces/dummy-shell-hooks/hooks/ansible/osoos/install_packages.yaml
- docs/source/examples/workspaces/dummy-shell-hooks/hooks/ansible/success_hook/success_hook.yaml
- docs/source/examples/workspaces/dummy-shell-hooks/layouts/dummy-layout.yml
- docs/source/examples/workspaces/dummy-shell-hooks/linchpin.conf
- docs/source/examples/workspaces/dummy-shell-hooks/localhost
- docs/source/examples/workspaces/dummy-shell-hooks/topologies/dummy-topology.yml
- linchpin/hooks/__init__.py
- linchpin/hooks/action_managers/subprocess_action_manager.py
Shell hook execution previously did not return anything, which would result in an exception being thrown even if the hooks were successful. This PR makes shell hook execution return 0, or the error code of the first error.  It also prints stderr to the console along with stdout.
Finally, this includes the integration test that was referenced in #898
> Fix lack of return code for shell hooks

- linchpin/provision/filter_plugins/get_pod_status.py
> Make openshift check pods for state instead of containers

- docs/source/examples/workspaces/dummy-hook-flags/PinFile
- docs/source/examples/workspaces/dummy-hook-flags/hooks/dummy-hooks.yml
- linchpin/cli/__init__.py
> Allow hooks to be written in a separate file

- linchpin/provision/filter_plugins/omit_filter.py
- linchpin/provision/roles/openstack/tasks/provision_os_keypair.yml
- linchpin/provision/roles/openstack/tasks/provision_os_network.yml
- linchpin/provision/roles/openstack/tasks/provision_os_object.yml
- linchpin/provision/roles/openstack/tasks/provision_os_router.yml
- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
- linchpin/provision/roles/openstack/tasks/provision_os_sg.yml
- linchpin/provision/roles/openstack/tasks/provision_os_subnet.yml
- linchpin/provision/roles/openstack/tasks/provision_os_volume.yml
fixes: #878 
De-duplicate tasks with help of omit filter
> Deduplicate tasks and fix env error in while provisioning volumes

- config/Dockerfiles/tests.d/inventory/01_template_inventory
- docs/source/examples/workspaces/dummy/PinFile
- docs/source/examples/workspaces/template-inventory/template-data/template-inventory.yml
- linchpin/cli/__init__.py
- linchpin/provision/roles/gather_resources/tasks/main.yml
- linchpin/utils/dataparser.py
We'll need to work to clean up the code, templates are a bit of a mess right now and I'm sure there's a weird edge case or two hiding somewhere.  But for now things seem to work roughly as expected and this won't hold up the next release
> Inventory template name

- config/Dockerfiles/centos7/Dockerfile
- config/Dockerfiles/fedora27/Dockerfile
- config/Dockerfiles/fedora28/Dockerfile
- config/Dockerfiles/run_tests.sh
- config/Dockerfiles/tests.d/inventory/02_json_inventory
- linchpin/InventoryFilters/JSONInventoryFormatter.py
- linchpin/cli/__init__.py
> Fix json inventory formatter configs

- config/Dockerfiles/JenkinsfileGHPRMerge
- config/Dockerfiles/JenkinsfileGHPRTrigger
- config/Dockerfiles/JenkinsfileMessageBusMerge
- config/Dockerfiles/JenkinsfileMessageBusTrigger
- config/s2i/jenkins/master/configuration/jobs/cd-linchpin-container/config.xml
- config/s2i/jenkins/master/configuration/jobs/ci-linchpin-messageBus-merge/config.xml
- config/s2i/jenkins/master/configuration/jobs/ci-linchpin-messageBus-trigger/config.xml
- config/s2i/jenkins/master/plugins.txt
We need jms-messaging-1.1.1 to send out nested arrays on fedmsg. These are the changes to resolve the syntax changes between 1.0.36 and 1.1.1
Signed-off-by: Johnny Bieren <jbieren@redhat.com>
> Updates for jms-messaging-1.1.1

- config/Dockerfiles/JenkinsfileMessageBusMerge
- config/Dockerfiles/JenkinsfileMessageBusTrigger
- config/Dockerfiles/fedora28/Dockerfile
- config/Dockerfiles/fedora29/Dockerfile
PR/945 should have updated the fedora containers
> Update Fedora containers

- docs/source/gs/pinfile.rst
- docs/source/includes/initialization.rst
> Updated documentation for linchpin init functionality

- config/Dockerfiles/tests.d/inventory/03_host-order
- docs/source/examples/workspaces/dummy/README.rst
- docs/source/examples/workspaces/host-group-order/PinFile
- docs/source/examples/workspaces/host-group-order/PinFile.json
- docs/source/examples/workspaces/host-group-order/README.rst
- linchpin/InventoryFilters/CFGInventoryFormatter.py
- linchpin/InventoryFilters/InventoryFilter.py
- linchpin/InventoryFilters/JSONInventoryFormatter.py
> Fix error with host_groups and hosts in layout being in different order

- config/s2i/jenkins/master/configuration/jobs/ci-linchpin-messageBus-merge/config.xml
- config/s2i/jenkins/master/configuration/jobs/ci-linchpin-messageBus-trigger/config.xml
- config/s2i/jenkins/master/plugins.txt
Signed-off-by: Johnny Bieren <jbieren@redhat.com>
> Small s2i updates for jms plugin

- linchpin/provision/roles/gather_resources/tasks/main.yml
> Add openshift resources to linchpin.latest and outputs

- linchpin/provision/roles/libvirt/tasks/teardown_libvirt_node.yml
> Fix libvirt destroy async error

- config/Dockerfiles/tests.d/libvirt/03_libvirt-network
- config/Dockerfiles/tests.d/libvirt/04_libvirt-network-dns
- docs/source/examples/workspaces/libvirt/PinFile
- linchpin/provision/roles/libvirt/files/schema.json
- linchpin/provision/roles/libvirt/templates/libvirt_network.xml.j2
$subject
fixes: #946 
To be merged after #966
> Enable dns attribute in libvirt network provisioning

- config/Dockerfiles/tests.d/aws/02_aws_ec2_vpc_net
- config/Dockerfiles/tests.d/aws/05_aws_ec2_vpc_endpoint
- docs/source/aws.rst
- docs/source/examples/workspaces/aws/PinFile
- docs/source/examples/workspaces/aws/topologies/aws-ec2-vpc-endpoint.yml
- linchpin/provision/filter_plugins/fetch_list_by_attr.py
- linchpin/provision/roles/aws/files/schema.json
- linchpin/provision/roles/aws/tasks/provision_aws_ec2_vpc_endpoint.yml
- linchpin/provision/roles/aws/tasks/teardown_aws_ec2_vpc_endpoint.yml
- linchpin/provision/roles/aws/tasks/teardown_resource_group.yml
- requirements.txt
Summary: 
22de7047 Added integration test for 05_aws_ec2_vpc_endpoint
892d0ed2 Updated documentation and examples for aws-ec2-vpc-endpoint
f00ca905 Updated playbooks in aws role to support aws_ec2_vpc_endpoint
cf7db20c Updated schema to support aws_ec2_vpc_endpoint
7439ab69 Update requirements.txt for compatible boto version
> Add support for aws_ec2_vpc_endpoint

- linchpin/provision/roles/openshift/tasks/provision_resource_group.yml
> Search for creds in workspace when they are not found in defaults

- linchpin/provision/roles/openshift/tasks/provision_resource_group.yml
> bugfix: Remove duplicate when, and add ignore_errors while resolving creds

- config/Dockerfiles/tests.d/aws/07_aws_ec2_template
- config/Dockerfiles/tests.d/inventory/01_template_inventory
- docs/source/examples/workspaces/aws/PinFile
- docs/source/examples/workspaces/template-inventory/PinFile
> Moved out template inventory test as provider specific test for aws

- docs/source/beaker.rst
- docs/source/credentials/beaker.rst
- docs/source/tutorials/beaker.rst
> Add Beaker Server tutorial

- docs/source/openstack.rst
After this, I'll have a few more PRs that add tables describing the topologies for the other OpenStack roles
> Update openstack docs

- docs/source/examples/workspaces/aws/PinFile
- docs/source/examples/workspaces/beaker/PinFile
- docs/source/examples/workspaces/duffy/PinFile
- docs/source/examples/workspaces/gcloud/PinFile
- docs/source/examples/workspaces/libvirt/PinFile
- docs/source/examples/workspaces/openstack/PinFile
- docs/source/examples/workspaces/ovirt/PinFile
- docs/source/examples/workspaces/rackspace/PinFile
> paramaterized examples

- docs/source/examples/workspaces/libvirt/PinFile
Fix errors in Libvirt PinFile that prevent the PinFile from being used without template data, as well as syntax errors.
> Fix errors in libvirt PinFile

- docs/source/examples/workspaces/ansible-hook/PinFile
- docs/source/examples/workspaces/ansible-hook/hooks/ping/ping.yml
- docs/source/examples/workspaces/aws-simple/PinFile
- docs/source/examples/workspaces/beaker-custom/PinFile
- docs/source/examples/workspaces/beaker-custom/localhost
- docs/source/examples/workspaces/beaker-custom/sshkey/Makefile
- docs/source/examples/workspaces/beaker-custom/sshkey/PURPOSE
- docs/source/examples/workspaces/beaker-custom/sshkey/runtest.sh
- docs/source/examples/workspaces/beaker-simple/PinFile
- docs/source/examples/workspaces/beaker-simple/localhost
- docs/source/examples/workspaces/beaker-whiteboard/PinFile
- docs/source/examples/workspaces/beaker-whiteboard/localhost
- docs/source/examples/workspaces/testinfra/PinFile
- docs/source/examples/workspaces/testinfra/hooks/testinfra/python.yml
- docs/source/examples/workspaces/testinfra/hooks/testinfra/test.sh
- docs/source/examples/workspaces/testinfra/hooks/testinfra/test_python.py
New examples:
- ansible hook
- beaker customization
- testinfra hook
simplified examples:
- openstack
- beaker
- aws
> More examples and simplify templates

- docs/source/tutorials/templating.rst
> Add tutorial on how to use linchpin template data

- docs/source/examples/workspaces/aws/PinFile
$subject 
fixes failures in develop branch
to be merged before #1032
> fixes to syntax errors in existing ec2-templates

- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
> Do not append count when there is only one instance to be provisioned

- linchpin/InventoryFilters/CFGInventoryFormatter.py
> Fix Inventory Generation failures when var is not a string

- docs/source/examples/workspaces/libvirt/PinFile
- linchpin/provision/roles/libvirt/files/schema.json
- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
- linchpin/provision/roles/libvirt/templates/libvirt_node.xml.j2
This change adds support for specifying the disk cache type for:
- VM base image via disk_cache parameter
- for each additional storage disk via cache parameter
> Libvirt VMs disks cache support

- docs/source/examples/workspaces/libvirt/PinFile
- docs/source/examples/workspaces/libvirt/custom.xml
- linchpin/provision/roles/libvirt/files/schema.json
- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
- linchpin/provision/roles/libvirt/templates/libvirt_node.xml.j2
> Fix storage location

- linchpin/version.py
$subject
Do not merge until related PRs to milestones are merged
> Release linchpin 1.7.3

- docs/source/tutorials/aws.rst
- docs/source/tutorials/beaker.rst
- docs/source/tutorials/templates/layout.rst
> Fix indentation in examples of tutorials

- docs/source/examples/workspaces/openstack/PinFile
- docs/source/examples/workspaces/openstack/topologies/os-vol-new.yml
$subject 
Update resource names to easily identify the provisioned resources.
> Updated resource_names with prefix ci-lp-cp-

- docs/source/examples/workspaces/openstack/PinFile
Updated the credentials to PSI infra structure. 
Summary:
updated network parameters to reflect the same networks in PSI 
@14rcole @p3ck
> Update examples to use provider network w.r.to PSI infra

- linchpin/validator/__init__.py
> Fix validation error on destroy when use_rundb_for_actions is enabled

- docs/source/aws.rst
- docs/source/examples/workspaces/aws/PinFile
- docs/source/examples/workspaces/aws/topologies/aws-ec2.yml
- docs/source/installation.rst
- linchpin/provision/roles/aws/files/schema.json
- linchpin/provision/roles/aws/tasks/provision_aws_sg.yml
This PR fixing issues for creating SecureGroup for AWS provider and
also some documentation improvements/fixes.
> Fixing AWS provider related stuff

- docs/source/custom_action_managers.rst
- docs/source/getting_started.rst
- docs/source/hooks.rst
- docs/source/hooks_cli_options.rst
- docs/source/hooks_examples.rst
- linchpin/hooks/__init__.py
Summary:
* Basic documentation for hooks
* Command line options for hooks
* Hooks examples
fixes #684
fixes #714
fixes #883
> Add basic documentation for hooks

- config/Dockerfiles/tests.d/openstack/09_os_keypair
- docs/source/examples/workspaces/openstack/PinFile
- docs/source/examples/workspaces/topologies/os-keypair.yml
- docs/source/openstack.rst
- linchpin/provision/roles/openstack/tasks/provision_os_keypair.yml
> Updated tests and documentation for os_keypair

- dev_setup/playbooks/roles/minishift/tasks/install_minishift_bin.yml
Sed task grabbing too much, and was preventing ansible from following links
> Fix task in dev setup that downloads minishift

- linchpin/__init__.py
- linchpin/linchpin.constants
- linchpin/provision/roles/openstack/tasks/provision_os_object.yml
- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
- linchpin/provision/roles/openstack/tasks/provision_os_volume.yml
- linchpin/provision/roles/openstack/tasks/provision_res_defs.yml
Fixes issue - https://github.com/CentOS-PaaS-SIG/linchpin/issues/1037
> Adding delimiter for user defined names in OpenStack

- linchpin/tests/InventoryFilters/test_CFGInventoryFormatter_pass.py
- linchpin/tests/InventoryFilters/test_InventoryFilter_pass.py
- linchpin/tests/InventoryFilters/test_JSONInventoryFormatter_pass.py
- linchpin/tests/mockdata/complex-inventory/correct-inventory
Fixes #1079 
There are a couple more unit tests failing locally for me.  I want to make sure they'll fail in Jenkins and if not, troubleshoot that.
> Fix errors in unit tests

- linchpin/rundb/tinyrundb.py
> Fix the deprecation Warning in tinydb

- docs/source/beaker.rst
- linchpin/provision/library/bkr_server.py
- linchpin/provision/roles/beaker/files/schema.json
Small update needed to support partition schema.
> Add support for beaker partitions in schema

- linchpin/version.py
$subject
This pull request is intended to test the infra migration which happened recently.
> Release v1.7.4

- config/Dockerfiles/JenkinsfileRelease
> Update variable name in JenkinsfileRelease

- config/Dockerfiles/tests.d/dummy/07-dummy-journal
- linchpin/shell/__init__.py
> fix linchpin journal error

- linchpin/version.py
$subject
Critical bugfix release
> release 1.7.4.1 

- config/Dockerfiles/Jenkinsfile
- config/Dockerfiles/JenkinsfileContainer
- config/Dockerfiles/JenkinsfileMergePR
- config/Dockerfiles/JenkinsfileRelease
- config/Dockerfiles/fedora30/Dockerfile
- config/s2i/create-containers.sh
- config/s2i/distros/fedora30-buildconfig-template.yaml
$subject
work in progress
Add fedora30 to container list and update references in Jenkins files
fix #1124
> Add fedora30 to container list

- config/Dockerfiles/JenkinsfileGHPRTrigger
- config/Dockerfiles/JenkinsfileUnitTests
- contra.yml
- playbooks/tests/unit_tests.yml
According to the recent discussion with @maneeshmehra 
It was decided that we continue to use contra-hdsl for unittests until a better alternative comes by. 
It was also mentioned that contra-hdsl will be supported for existing customers.
fixes #1167
> Fall back to contra-hdsl

- linchpin/FilterUtils/FilterUtils.py
- linchpin/provision/roles/beaker/tasks/get_job_structure.yml
- linchpin/provision/roles/beaker/tasks/get_job_structure2.yml
- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
- linchpin/provision/roles/beaker/tasks/teardown_resource_group.yml
- requirements.txt
- setup.py
Summary:
A bug was recently introduced in linchpin beaker making it unable to provision resource inventory and destroy them.
Committer: samvaran kashyap <samvaran.kashyap@gmail.com>
fixes: #1179 1179
> Update playbooks to fix bug in beaker destroy

- config/Dockerfiles/JenkinsfileGHPRMerge
- src/org/centos/pipeline/LinchpinPipelineUtils.groovy
- vars/linchpinPipelineUtils.groovy
> Move getChangedFile function to utils

- config/Dockerfiles/JenkinsfileGHPRMerge
- src/org/centos/pipeline/LinchpinPipelineUtils.groovy
- vars/linchpinPipelineUtils.groovy
The given PR is creating issues with the merge requests of linchpin
Reverts CentOS-PaaS-SIG/linchpin#1098
> Revert "Move getChangedFile function to utils"

- appimage.yml
> Linchpin AppImage on release

- config/Dockerfiles/fedora29/Dockerfile
- config/Dockerfiles/tests.d/libvirt/03_libvirt-network
- linchpin/version.py
Release linchpin 1.7.6 
Should be merged after #1187 and #1176 #1115 are merged
> Release linchpin 1.7.6

- linchpin/version.py
With a critical bug fix in requirements.txt , we had to release 1.7.6.1
> release 1.7.6.1

- config/Dockerfiles/JenkinsfileRelease
Disable container releases until its fixed.
releated to #1194
> disable container releases until it is fixed

- .travis.yml
- docs/source/advanced/layouts.rst
- docs/source/includes/provisioning.rst
- linchpin/__init__.py
- linchpin/ansible_runner.py
- linchpin/provision/roles/dummy/tasks/provision_res_defs.yml
- linchpin/provision/roles/dummy/tasks/teardown_res_defs.yml
- linchpin/provision/roles/gather_resources/tasks/main.yml
- linchpin/provision/roles/gcloud/tasks/provision_res_defs.yml
- linchpin/provision/roles/libvirt/tasks/provision_res_defs.yml
- linchpin/provision/roles/nummy/tasks/provision_res_defs.yml
- linchpin/provision/roles/nummy/tasks/teardown_res_defs.yml
- linchpin/provision/roles/openstack/tasks/provision_res_defs.yml
- linchpin/provision/roles/ovirt/tasks/provision_res_defs.yml
- linchpin/shell/__init__.py
- linchpin/tests/test_init_pass.py
- playbooks/tests/unit_tests.yml
> Add option to disable uhash for specific targets via the command line

- setup.py
This ensures a description of the project is present on PyPI. A small
issue with the loading of requirements is also corrected.
> setup.py: Configure 'long_description'

- docs/source/providers.rst
> add vmware to providers index

- linchpin/provision/roles/aws/files/schema.json
- linchpin/provision/roles/aws/tasks/provision_aws_ec2_key.yml
- linchpin/provision/roles/openstack/files/schema.json
> Fix aws key bug

- config/s2i/jenkins/master-downstream/configuration/jobs/ci-linchpin-messageBus-merge/config.xml
- config/s2i/jenkins/master-downstream/configuration/jobs/ci-linchpin-messageBus-trigger/config.xml
Add back missing jobs to linchpin
add messageBus-merge and messageBus-trigger jobs to downstream jenkins
> add messageBus-merge and messageBus-trigger jobs to downstream jenkins

- config/Dockerfiles/JenkinsfileContainer
> Update project name to fetch from environment variable

- config/s2i/create-containers.sh
> Update create-containers.sh to fetch project variable from environment

- docs/source/examples/workspaces/openstack/topologies/os-keypair.yml
- docs/source/openstack.rst
Signed-off-by: Lukas Bednar <lbednar@redhat.com>
> doc: fix broken links in openstack topology exampples

- config/s2i/create-containers.sh
> PR for fixing privileged psi tests

- requirements.txt
- setup.py
Moved pytest from requirements.txt to setup.py
fixes #1260
> Move pytest from requirements.txt to pytest

- config/Dockerfiles/tests.d/inventory/01_template_inventory
- docs/source/examples/workspaces/libvirt-cirros/PinFile
- docs/source/examples/workspaces/libvirt-cirros/README.rst
- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
Bugfix found while troubleshooting libvirt provider. 
Might be a  partial cause for #1279
> bugfix: libvirt hangs when cloud-config is not provided in Pinfile

- docs/source/examples/workspaces/beaker-simple/PinFile
- linchpin/hooks/built_ins/__init__.py
- linchpin/hooks/built_ins/beaker_log/boot_log.yml
- linchpin/hooks/built_ins/beaker_log/templates/log.j2
> Beaker log collector hook

- config/Dockerfiles/tests.d/azure/03_azure_virtual_subnet
- linchpin/provision/roles/azure/files/schema.json
- linchpin/provision/roles/azure/tasks/main.yml
- linchpin/provision/roles/azure/tasks/provision_azure_virtual_subnet.yml
- linchpin/provision/roles/azure/tasks/provision_res_defs.yml
- linchpin/provision/roles/azure/tasks/teardown_azure_virtual_subnet.yml
Added Azure subnet creation and destruction
> Azure subnet

- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
- requirements.txt
$subject 
Jenkins is trying to install 2.9.0b1 failing on installations
> Restrict ansible 2.8.4

- config/Dockerfiles/tests.d/azure/06_azure_res_grp
- docs/source/examples/workspaces/azure/PinFile
- linchpin/provision/roles/azure/files/schema.json
- linchpin/provision/roles/azure/tasks/main.yml
- linchpin/provision/roles/azure/tasks/provision_azure_resource_group.yml
- linchpin/provision/roles/azure/tasks/provision_azure_vm.yml
- linchpin/provision/roles/azure/tasks/teardown_azure_resource_group.yml
- linchpin/provision/roles/azure/tasks/teardown_resource_group.yml
- linchpin/provision/roles/gather_resources/tasks/main.yml
creation and destruction of Azure Resource Group
> Manage res group azure

- linchpin/FilterUtils/FilterUtils.py
- linchpin/provision/filter_plugins/fetch_os_server_names.py
- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
- linchpin/tests/InventoryFilters/test_FilterPlugins_pass.py
> Fix openstack teardown bug

- docs/source/azure.rst
- docs/source/examples/workspaces/azure/PinFile
- linchpin/provision/roles/azure/files/defaults.yml
- linchpin/provision/roles/azure/files/schema.json
- linchpin/provision/roles/azure/tasks/provision_azure_virtual_network.yml
- linchpin/provision/roles/azure/tasks/provision_azure_virtual_subnet.yml
- linchpin/provision/roles/azure/tasks/provision_azure_vm.yml
- linchpin/provision/roles/azure/tasks/teardown_res_defs.yml
- linchpin/provision/roles/azure/tasks/teardown_resource_group.yml
Added an Azure wrapper allowing user create a vm without creating all the virtual network virtual subnet
> Azure wrapper

- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
> [bug fix] fix: "vm shutt off" after provision

- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
> Fix mac_ip bug from issue #1335

- docs/source/examples/workspaces/openshift/PinFile
- linchpin/hooks/built_ins/__init__.py
- linchpin/hooks/built_ins/ocp_container_boot_log/boot_log.yml
- linchpin/hooks/built_ins/ocp_container_boot_log/templates/log.j2
> Collect OCP logs

- docs/source/examples/workspaces/beaker-simple/PinFile
- linchpin/hooks/built_ins/res_check/beaker.yml
- linchpin/hooks/built_ins/res_check/bkr_recipeset.yml
- linchpin/hooks/built_ins/res_check/bkr_server.yml
- linchpin/provision/library/bkr_distro_facts.py
> Beaker check resources hook

- config/Dockerfiles/linchpin/Dockerfile
This fixes the bug sent to the linchpin mailing list
> Update linchpin container to fedora 30

- docs/source/examples/workspaces/dummy-hook-flags/hooks/dummy-hooks.yml
- linchpin/hooks/action_managers/ansible_action_manager.py
- linchpin/hooks/action_managers/nodejs_action_manager.py
- linchpin/hooks/action_managers/python_action_manager.py
- linchpin/hooks/action_managers/ruby_action_manager.py
- linchpin/hooks/action_managers/subprocess_action_manager.py
Fix error in hooks schema causing vault_password_file to not be read
Signed-off-by: 14rcole <rycole@redhat.com>
> Fix schema for hooks

- config/Dockerfiles/Jenkinsfile
- config/Dockerfiles/tests.d/openstack/10_openstack_libvirt
- config/Dockerfiles/tests.d/openstack/10_openstack_libvirt.sh
- docs/source/examples/workspaces/libvirt/PinFile
- docs/source/examples/workspaces/openstack-libvirt/PinFile
- docs/source/examples/workspaces/openstack-libvirt/README.rst
- docs/source/examples/workspaces/openstack-libvirt/hooks/ansible/install_linchpin/install.yaml
- docs/source/examples/workspaces/openstack-libvirt/hooks/ansible/run_linchpin_libvirt_tests/run_tests.yaml
- docs/source/examples/workspaces/openstack-libvirt/linchpin.conf
Fixes many issues by running libvirt inside openstack instances.
Fixes: 
#1186 
#1190 
#1268
> Enable libvirt tests 

- docs/source/aws.rst
> Deleted broken urls

- linchpin/provision/roles/dependencies/tasks/main.yml
> Fix syntax errors on linchpin setup.yml

- linchpin/version.py
> Release v1.8.2

- docs/source/BrokenLinkFilter.py
Added broken links filter
Broken links in rst documentation could be found with this
> Added broken links filter

- linchpin/provision/roles/azure/files/schema.json
- linchpin/provision/roles/azure/tasks/main.yml
- linchpin/provision/roles/azure/tasks/provision_azure_network_interface.yml
- linchpin/provision/roles/azure/tasks/provision_azure_vm.yml
- linchpin/provision/roles/gather_resources/tasks/main.yml
> Added network interface and fix a bug inside provision_vm

- linchpin/tests/test_init_pass.py
- playbooks/tests/unit_tests.yml
bugfix: set maxdiff to none for python3 testing
Update unit tests to use python3 env
> Update unit tests contra-hdsl

- docs/source/examples/workspaces/azure/PinFile
- linchpin/provision/roles/azure/files/schema.json
- linchpin/provision/roles/azure/tasks/teardown_azure_vm.yml
> Added deep clean

- docs/source/azure.rst
> Add IAM instruction

- config/Dockerfiles/tests.d/azure/06_azure_res_grp
- docs/source/examples/workspaces/azure/PinFile
> Added example resource into resource group integration test

- docs/source/managing_resources.rst
Removed an additional 'o' in the word 'Toopologies'
> Managing Resources: Topology spelling corrected

- config/Dockerfiles/tests.d/openstack/11_os-port
- config/Dockerfiles/tests.d/openstack/12_os-zone
- docs/source/examples/workspaces/openstack/PinFile
- linchpin/provision/roles/openstack/files/schema.json
- linchpin/provision/roles/openstack/tasks/provision_os_port.yml
- linchpin/provision/roles/openstack/tasks/provision_os_zone.yml
- linchpin/provision/roles/openstack/tasks/teardown_os_port.yml
- linchpin/provision/roles/openstack/tasks/teardown_os_zone.yml
- linchpin/provision/roles/openstack/tasks/teardown_resource_group.yml
The following PR adds support for the os_zone module however the integration tests are disabled for this module due to unavailable infra.
fixes #823 
to be merged after #1379
> (Preview feature) Add support for os_zone module

- config/Dockerfiles/tests.d/openstack/11_os-port
- config/Dockerfiles/tests.d/openstack/12_os-zone
- config/Dockerfiles/tests.d/openstack/13_os-recordset
- docs/source/examples/workspaces/openstack/PinFile
- linchpin/provision/roles/openstack/files/schema.json
- linchpin/provision/roles/openstack/tasks/provision_os_port.yml
- linchpin/provision/roles/openstack/tasks/provision_os_recordset.yml
- linchpin/provision/roles/openstack/tasks/provision_os_zone.yml
- linchpin/provision/roles/openstack/tasks/teardown_os_port.yml
- linchpin/provision/roles/openstack/tasks/teardown_os_recordset.yml
- linchpin/provision/roles/openstack/tasks/teardown_os_zone.yml
- linchpin/provision/roles/openstack/tasks/teardown_resource_group.yml
The following PR adds support for the os_recordset module however the integration tests are disabled for this module due to unavailable infra.
fixes #822 
to be merged after #1382
> (Preview feature) Add support for os_recordset module 

- linchpin/FilterUtils/FilterUtils.py
- linchpin/provision/filter_plugins/write_to_file.py
- linchpin/provision/roles/gather_resources/tasks/main.yml
> Update generate resources task to avoid bug in python3_virtualenvironments

- linchpin/__init__.py
Fixes Issue #1413 
Caused due to improper indentation. 
I still wonder why it was not caught earlier.
> bugfix: fix destroy issue #1413

- linchpin/provision/module_utils/linchpin_rundb.py
This will fix the error I was getting when testing #1402
> Fix error preventing linchpin destroy from working

- linchpin/provision/roles/libvirt/templates/libvirt_node.xml.j2
This fixes an issue that was posted on Google chat.  It looks like at some point an argument was removed from a task in linchpin, but the indices in the template remained the same
> Adjust indices in libvirt node template to match changes in Ansible

- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
- linchpin/provision/roles/libvirt/tasks/teardown_libvirt_node.yml
This is a continuation for PR#1429 to provide a fix for issue #1425.
> Fix additional indices for libvirt define node tasks

- docs/source/advanced/cfgs.rst
- docs/source/developing_roles.rst
- docs/source/gs/pinfile.rst
- docs/source/resources.rst
Add documentation on how to develop Ansible Galaxy roles for LinchPin
> WIP: Add role documentation

- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
This will fix the last issue blocking release
> Fix issues preventing beaker resources from being generated properly

- linchpin/version.py
Release linchpin version 1.9.0
> Release linchpin version 1.9.0

- MANIFEST.in
Add missing azure-requirements to Manifest.in
> Add azure requirements to MANIFEST.in

- config/Dockerfiles/tests.d/openstack/08_os_subnet
> disable test until the bug is fixed with openstack subnet

- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
> Make libvirt use the add_res_data function

- config/Dockerfiles/tests.d/azure/07_azure_nic
- docs/source/examples/workspaces/azure/PinFile
- linchpin/provision/roles/azure/tasks/teardown_azure_network_interface.yml
Added NIC teardown and Integration test to Azure
> Added nic teardown

- config/Dockerfiles/tests.d/azure/08_azure_multi_vm
- docs/source/azure.rst
- docs/source/examples/workspaces/azure/PinFile
- linchpin/provision/roles/azure/files/schema.json
- linchpin/provision/roles/azure/tasks/provisionVM.yml
- linchpin/provision/roles/azure/tasks/provision_azure_vm.yml
- linchpin/provision/roles/azure/tasks/teardownVM.yml
- linchpin/provision/roles/azure/tasks/teardown_azure_vm.yml
> Add count azure

- rpmbuild.sh
Verified with the following build and docker containers `fedora:30` and `centos:7`:
https://copr.fedorainfracloud.org/coprs/alexbmasis/linchpin/build/1113023/
> Fix CentOS RPM

- docs/source/examples/workspaces/openstack-os-floating-ip/PinFile
- docs/source/examples/workspaces/openstack-os-floating-ip/README.rst
- docs/source/examples/workspaces/openstack-os-floating-ip/linchpin.conf
- linchpin/provision/roles/openstack/files/schema.json
- linchpin/provision/roles/openstack/tasks/provision_os_floating_ip.yml
- linchpin/provision/roles/openstack/tasks/teardown_os_floating_ip.yml
Note: Due to unsupported infrastructure. The integration test has been omitted. 
fixes: #1390
> Preview: Add support for os_floating_ip module

- linchpin/__init__.py
> Fix an AttributeError when LinchpinAPI imported in another app

- linchpin.json
Temporary fix for Ansible 2.9 incompatibility with Python 2.7
> RPM support all providers

- docs/source/examples/workspaces/azure/PinFile
create a new private image and fix the bug caused by it
> bugfix: Update private image path in examples

- linchpin/rundb/drivers.py
> fixes: #1503 Linchpin clean installation with Python 3 requires pymongo

- docs/source/examples/workspaces/azure/PinFile
> Bugfix: fix azure private image bug

- linchpin/FilterUtils/FilterUtils.py
- linchpin/provision/filter_plugins/convert_to_json.py
- linchpin/provision/roles/aws/tasks/teardown_resource_group.yml
- linchpin/provision/roles/azure/tasks/provisionVM.yml
- linchpin/provision/roles/azure/tasks/teardown_resource_group.yml
- linchpin/provision/roles/beaker/tasks/teardown_resource_group.yml
- linchpin/provision/roles/docker/tasks/teardown_resource_group.yml
- linchpin/provision/roles/duffy/tasks/teardown_resource_group.yml
- linchpin/provision/roles/openstack/tasks/teardown_resource_group.yml
> Update rundb calls in playbooks

- linchpin/hooks/__init__.py
> bugfix: Update builtin hooks return var

- linchpin/provision/roles/azure/tasks/provisionVM.yml
- linchpin/provision/roles/azure/tasks/teardownVM.yml
- linchpin/provision/roles/azure/tasks/teardown_azure_vm.yml
- linchpin/provision/roles/azure/tasks/teardown_resource_group.yml
> Improved Deep clean Feature

- linchpin/version.py
> Release linchpin 1.9.1.1

- docs/source/includes/aws_creds.rst
- linchpin/linchpin.constants
- linchpin/shell/__init__.py
- playbooks/tests/unit_tests.yml
> Added default creds-path and documentation

- config/Dockerfiles/JenkinsfileRelease
Fixes failures in cd-release-process jenkins job.
> Update release container to fedora30

- linchpin/ansible_runner.py
> Add support for vault-password-file in ansible api

- config/Dockerfiles/rhel7/Dockerfile
- config/s2i/distros/rhel7-buildconfig-template.yaml
$subject
This would be a 1st step in adding rhel7 into the upstream testing. 
The Dockerfiles needs to be merged first before
> Add rhel7 s2i buildconfig and Dockerfile

- linchpin/__init__.py
- linchpin/linchpin.constants
- linchpin/provision/callback_plugins/zmq.py
- linchpin/shell/__init__.py
Fixes #1530 and partially #1519 
Notice the 'mock' module - it was used to avoid additional 'if' statements.
> Option to disable progress bar

- docs/source/getting_started.rst
- docs/source/monitor.rst
- linchpin/__init__.py
- linchpin/provision/action_plugins/dummy.py
- linchpin/provision/action_plugins/ec2.py
- linchpin/provision/callback_plugins/zmq.py
- linchpin/shell/__init__.py
> Option to disable monitor and multiprocessing

- linchpin/__init__.py
- linchpin/provision/action_plugins/ec2.py
- requirements.txt
> Fixes magic mock import issues in multiple versions of python

- .travis.yml
- config/Dockerfiles/linchpin-install.sh
- linchpin/__init__.py
- linchpin/cli/__init__.py
- linchpin/provision/action_plugins/libvirt_network.py
- linchpin/provision/action_plugins/libvirt_node.py
- linchpin/provision/action_plugins/libvirt_storage.py
- setup.py
Also add radon tests to linchpin unit tests, but do not require a certain score in order to pass
> Decrease cyclomatic complexity of do_action function

- docs/source/examples/workspaces/azure/PinFile
Fix CI, now we have our own private image without any leftover. @abraverm Could you please rebase this into your pr? It will fix the failing tests
> Fixed private image

- docs/source/examples/workspaces/azure/PinFile
This is a preparation towards testing different authentication methods (AD)
> Make profile a variable in Azure example

- linchpin/provision/roles/azure/tasks/provision_azure_network_interface.yml
Added resource type to the output for Azure Network Interface. It will appear in azure_nic.output
> Added res_type to Azure Network Interface

- config/Dockerfiles/tests.d/azure/10_azure_nsg
- docs/source/azure.rst
- docs/source/examples/workspaces/azure/PinFile
- linchpin/provision/roles/azure/files/schema.json
- linchpin/provision/roles/azure/tasks/main.yml
- linchpin/provision/roles/azure/tasks/provision_azure_nsg.yml
- linchpin/provision/roles/azure/tasks/teardown_azure_nsg.yml
- linchpin/provision/roles/gather_resources/tasks/main.yml
> Azure network security group

- docs/source/azure.rst
Fixed and added the rest documentation for Azure
> Fixed and added the rest documentation

- linchpin/provision/roles/libvirt/files/schema.json
- linchpin/provision/roles/libvirt/templates/libvirt_network.xml.j2
Introduce the ability to pass dnsmasq options to the libvirt network definition.
> Add support for providing dnsmasq options to libvirt network definition

- linchpin/version.py
> Release Linchpin v1.9.2

- docs/source/installation.rst
- docs/source/managing_resources.rst
- docs/source/workflow.rst
The master branch is ahead of develop branch. 
The following commits need to merge into the develop branch in order to resolve conflicts in the release process.
> Align develop branch with master branch 

- rpmbuild.sh
> WIP: Fix CentOS RPM build

- docs/source/examples/workspaces/aws-simple/PinFile
- docs/source/examples/workspaces/aws-simple/linchpin.conf
- linchpin/hooks/built_ins/res_check/aws.yml
- linchpin/hooks/built_ins/res_check/aws_ec2.yml
fixes #1585 
With the built-in pre-up hook, the user can check if required resources exists for creating ec2 instance:
- security group
- image
- region
> AWS EC2 resource check

- linchpin/FilterUtils/FilterUtils.py
> Add file permissions to keyfiles created

- requirements.txt
This will fix the failures in #1611
> Add gitdb as a requirement

- linchpin/FilterUtils/FilterUtils.py
- linchpin/__init__.py
- linchpin/provision/action_plugins/ec2.py
- linchpin/provision/action_plugins/libvirt_network.py
- linchpin/provision/action_plugins/libvirt_node.py
- linchpin/provision/action_plugins/libvirt_storage.py
- linchpin/provision/filter_plugins/cpu_to_int.py
- linchpin/provision/filter_plugins/memory_to_int.py
- setup.py
The following are flak8 fixes that need to be merged in order to make GitHub linting action successful.
> Flake8 fixes to make github linting actions to succeed

- .github/workflows/linting.yml
- .github/workflows/multicontainertesting.yml
- requirements.txt
> Disable fail-fast mode to run all tests in all operating systems

- linchpin/provision/roles/dependencies/tasks/beaker_deps.yml
- setup.py
Fixes #1581 gssapi beaker dependency issue.
> Fixes #1581 with the gssapi overlap issue for beaker dependencies.

- .github/runmocktests.sh
Added azure mock test to github action
> Added azure mock test to github action

- .github/workflows/linting.yml
- .github/workflows/molecule-tests-centos7.yml
- .github/workflows/molecule-tests.yml
- linchpin/provision/roles/openstack/molecule/delegated/molecule.yml
- linchpin/provision/roles/openstack/molecule/shared/playbook.yml
- linchpin/provision/roles/openstack/molecule/shared/templates/os_stack.yml
- linchpin/provision/roles/openstack/tasks/teardown_os_keypair.yml
> Test openstack role using molecule in GitHub Actions

- .github/workflows/multicontainertesting.yml
This PR does not set a failure condition for the code complexity test.  That can come after we decrease the complexity
Resolves #1674
> Test code complexity in GitHub Actions

- docs/source/examples/workspaces/azure/linchpin.conf
Since linchpin init fetches from upstream
This PR needs to be merged before #1682 is merged
> Fix linchpin.conf for azure workspace

- .github/workflows/linting.yml
- .github/workflows/molecule-tests-centos7.yml
- .github/workflows/molecule-tests.yml
- .github/workflows/multicontainertesting.yml
> Disable linting molecule and container testing after push

- config/Dockerfiles/tests.d/run.sh
- docs/source/examples/workspaces/azure/PinFile
- linchpin/provision/roles/azure/tasks/teardownManageddisk.yml
- linchpin/provision/roles/azure/tasks/teardownVirtualnetwork.yml
- linchpin/provision/roles/azure/tasks/teardown_azure_vm.yml
Improved deep clean for multiple VM and fix the mock data issue. Should partially  #1681 and fix #1692
> WIP Improved deep clean for multiple vm and fix the mock data issue 

- .github/workflows/multicontainertesting.yml
- .gitignore
- linchpin/ansible_runner.py
- linchpin/cli/__init__.py
- linchpin/hooks/action_managers/nodejs_action_manager.py
- linchpin/hooks/action_managers/ruby_action_manager.py
- linchpin/provision/roles/setup/tasks/setup_dnf_deps.yml
- linchpin/tests/__init__.py
- linchpin/tests/cli/tests_init_fail.py
- linchpin/tests/cli/tests_init_pass.py
- linchpin/tests/hooks/action_managers/test_ansible_action_manager.py
- linchpin/tests/hooks/action_managers/test_nodejs_action_manager.py
- linchpin/tests/hooks/action_managers/test_ruby_action_manager.py
- linchpin/tests/mockdata/dummy/PinFile
- linchpin/tests/mockdata/dummy/hooks/ansible/success_hook/success_hook.yaml
- linchpin/tests/mockdata/dummy/hooks/dummy-hooks.yml
- linchpin/tests/mockdata/dummy/hooks/nodejs/success_hook/success_hook.js
- linchpin/tests/mockdata/dummy/hooks/ruby/success_hook/success_hook.rb
- linchpin/tests/mockdata/templates/template-inventory.yml
Improve unit test coverage to 70% and make tests fail if coverage drops below that amount
> Improve code coverage to 70%

- docs/source/examples/workspaces/libvirt/linchpin.conf
Need to link linchpin-mock.conf to linchpin.conf inorder to run mock tests inside github actions 
related to #1542
> Update linchpin.conf inside workspace

- linchpin/version.py
Release linchpin 2.0.0 
should be merged after #1705
> Release linchpin 2.0.0

- linchpin/provision/roles/aws/tasks/provision_aws_ec2.yml
> Fix bug in which provisioning AWS fails when count is not set

- linchpin/shell/__init__.py
> Fix bug preventing no_monitor from being set in linchpin.conf

- .github/workflows/packaging.yml
> Disable packaging job until its fixed and tested

- docs/source/examples/workspaces/azure/PinFile
- linchpin/provision/roles/azure/files/schema.json
- linchpin/provision/roles/azure/tasks/provisionVM.yml
Enabled multiple nic for azure
> Enabled multiple nic

- config/Dockerfiles/linchpin/Dockerfile
- docs/source/installation.rst
- setup.py
Updates linchpin dockerfile and documentation. 
fixes #1719
> fix and Update docker file, documentation

- docs/source/examples/workspaces/openstack-ocp/PinFile
- docs/source/examples/workspaces/openstack-ocp/install.yaml
- docs/source/examples/workspaces/openstack-ocp/ocp-run.yml
- docs/source/examples/workspaces/openstack-ocp/run_tests.yml
> Added OCP workplace

- requirements.txt
> Update requirements to fix openstacksdk dependency error

- linchpin/__init__.py
> Fix bug causing provisioning to hang and preventing hooks from being run
