- README.md
- docs/source/intro_getting_started.rst
Documenting more than one level of folders is unnecessary for
the top level docs overview. All that does is introduce more
places where manual changes need to be made to keep the tree
in sync with the documented trees (and these two trees were
both already out of sync with the actual project tree). Reducing
it to one level of directory makes this easier to maintain,
as the top level structure of the project should change much
less frequently than the internals.
> Reduce documentation to one level

- provision/roles/output_writer/tasks/main.yml
We should be testing our work before committing. This is a simple fix which should not have been committed without review.
> fix async spelling

- provision/roles/openstack/tasks/provision_os_keypair.yml
- provision/site.yml
Added missing conditional for keypair provisioning. 
removed  *_grp_vars , As we can access the *_grp_vars inside the roles , we need not pass them as parameters to the roles again . (which might create a recursive loop.)
> added missing conditional in keypair provisioning and cleaned unnecessary vars

- provision/roles/openstack/tasks/provision_os_server.yml
fixed multiple network provisioning of openstack servers  for more details checkout the issue[(https://github.com/CentOS-PaaS-SIG/linch-pin/issues/49)]
> fixed bug with respect to multiple network provisioning of os_server

- provision/filter_plugins/duffy_inventory.py
This fixes host_vars getting assigned the same value across all hosts. Now the hosts_vars get assigned properly.
> make_host_vars should assign proper variable

- README.md
Readme recommends to use python-virtualenv with /usr/bin/virtualenvwrapper.sh, virtualenvwrapper.sh is part of python-virtualenvwrapper, so it also needs to be installed.
Tested on Fedora25 and RHEL-7.2
> README.md - install python-virtualenvwrapper

- linchpin_config.yml
- provision/roles/common/tasks/main.yml
> fixed PR #68 schema_check cannot find default schema outside linch-pin

- setup.py
revert back to list_all_files because findall function in setuptools is skipping subpackages causing linchpin 0.8.3, 0.8.4 builds fail while installing through pip.
> bugfix: revert back to list_all_files in setup.py

- linchpin_api/v1/api.py
- setup.py
If, for some reason, we can't find the linchpin_config.yml in the initial paths, use the default one in the package. It should be somewhere in the sys.path.
> Add more default paths to look for linchpin_config

- ex_topo/ex_gcloud_gce.yml
- library/gce.py
- provision/roles/gcloud/tasks/provision_gcloud_gce.yml
- provision/roles/gcloud/tasks/provision_resource_group.yml
- provision/roles/output_writer/tasks/main.yml
- provision/roles/output_writer/tasks/wait_on_gcloud_gce.yml
fixes #100 
Summary:
- Linchpin GCE provisioning/teardown faster than ever using upstream Ansible module ( no changes made to upstream module) 
- Borrowed upstream gce module for count based provisioning.
- Updated example of gcloud_gce
- Changed way of handling gce_creds, added support for *.json file in vars folder. Need not create a separate yaml file for credentials. 
- Updated provision playbooks and output writer clear outputs.
Note:
- Inventory gen works seamlessly without any changes
> linchpin Gcloud performance fix 

- InventoryFilters/GenericInventory.py
- InventoryFilters/InventoryProviders.py
- InventoryFilters/LibvirtInventory.py
- cli/cli.py
- examples/topology/libvirt_complete.yml
- linchpin_api/v1/invoke_playbooks.py
- provision/filter_plugins/libvirt_inv.py
- provision/roles/inventory_gen/tasks/main.yml
- provision/roles/inventory_gen/templates/libvirt_inventory_formatter.j2
- provision/roles/libvirt/tasks/copy_image_src.yml
- provision/roles/libvirt/tasks/main.yml
- provision/roles/libvirt/tasks/provision_libvirt_node.yml
- provision/roles/libvirt/tasks/provision_res_defs.yml
- provision/roles/libvirt/tasks/teardown_libvirt_node.yml
- provision/roles/libvirt/templates/libvirt_node.xml.j2
- provision/roles/openstack/tasks/main.yml
- provision/roles/openstack/tasks/provision_os_server.yml
- provision/roles/openstack/tasks/provision_resource_group.yml
- provision/roles/output_writer/tasks/main.yml
- requirements.txt
This PR fixes #98 and #154, as described below:
* Reworked libvirt provisioning 
* Renamed libvirt_nodes to reflect resource_group res_name and count, separated by an underscore
* Determine IP addresses of nodes for output and inventory generation
* Add teardown_node functionality (it works!!!)
* Copying source image name reflects libvirt_node name
* Added libvirt-python to requirements.txt
* Update filter_plugins to allow for Libvirt  
* Added libvirt_inv filter_plugin
* Added LibvirtInventory class to generate a proper inventory for libvirt topologies
* Added LibvirtInventory to GenericInventory and InventoryProviders
* Updated libvirt_complete.yml example
* remove libvirt_storage usage (moved to v1.1.0)
* remove multiple network definitions (only one allowed at this time)
* textual …
> Completed Libvirt plugin

- README.rst
The link to CONTRIBUTING.rst was pointing to master. However, master is intended to be stable only. Since the github front page points to develop branch, it makes sense to update this link in this way. It also requires a Pull Request to merge from develop to master. I believe the process to merge from develop to master should be much more controlled. Thus, this simple PR will fixup the needed link.
> Fixup contributing link to point to develop

- provision/roles/aws/tasks/provision_aws_ec2.yml
- provision/site.yml
- setup.py
Summary :
-   While initiating provisioning , it is observed that linchpin cli passes path of linchpin_config.yaml
file in linchpin_config extra var. However , its not being used while resolving the linchpin config file
due to a typo. This current commit resolves the config resolution issue of linchpin.
-   Currently , Provisioning of aws_ec2 instances are failing when res_grp_vars in undefined due to the  fact res_grp_vars are being used as instance tags while provisioning ec2 instance. In the current commit fixes the bug by setting resource_group_name and res_name as  default values of res_grp_vars for any instance when the res_grp_vars are undefined in topology.
- Resolves : issue #167
> Hot fixes : linchpin_config resolution , aws_ec2 default instance tags #167

- cli/cli.py
Fixes #172
* Added **outputfolder_path** variable to lp_drop().  It's also included in lp_rise(), and it is needed by both methods to allow the Ansible defaults to be used that are defined in various playbooks.
* Removed code that assembles and defines the **topology_output_file** variable.  Based on my understanding of the intent of the existing code, this variable is intended to allow users to override the default topology output file path that's constructed by the playbooks with Ansible variables.  By setting it in cli.py, an issue was identified where the defaults in the playbooks would never be used.
> fix for topology output paths

- docs/source/config_general.rst
`linchpin init` creates an "inventories" dir, not an "inventory" dir, so
I've updated the docs accordingly.
> Docs reflect correct "inventories" dir

- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
Having the "register:" declaration in there twice was causing ansible to
throw a warning on this task.
> Only register openstack provision outputs once

- requirements.txt
Running into issues when installing linchpin. Seems one of its packages it depends on needs a version of babel not equal too 2.4.0. Switching to a minimum version of 2.3.4 allows the install to work.
> Declare babel package with a minimum version.

- linchpin/__init__.py
- linchpin/api/__init__.py
- linchpin/api/invoke_playbooks.py
- linchpin/context.py
- setup.py
This commit improves linch-pins compatibility with Python 2 and Python 3. Changes consist of fixing import statements, checking if dictionary objects have attributes and using built in functions. More details can be found in each commit.
> Enhancements for Python compatibility

- linchpin/api/__init__.py
A module not found error is being raised when installing linch-pin using Python3.
Setting the full path allows linch-pin install on Python2 & Python3 to be successful.
> Give the full path for importing PlaybookCallback.

- linchpin/api/callbacks.py
- linchpin/cli/context.py
Addresses API calls which do not use the console, The callback now
stores failed results so they can be returned.
> Add failed results to callbacks.py

- linchpin/defaults/schemas/schema_v2.json
- linchpin/defaults/schemas/schema_v3.json
- linchpin/defaults/schemas/schema_v4.json
- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
Surprisingly , though linchpin can create security groups on openstack , it cannot assign security groups to the provisioned instances. 
Current pr resolves this issue by adding security_groups parameter to os_server resource which accepts comma separated values of security groups in topology.
> Develop :: Added support for security_groups parameter in os_server resource 

- CONTRIBUTING.rst
Fixes #185
Added a few paragraphs to explain how develop and master differ,
including tagging releases, branching, pypi and RPMs.
> Explain the release process

- docs/source/topologies_beaker.rst
- linchpin/defaults/schemas/schema_v4.json
- linchpin/examples/topologies/beaker_fedoraproject_server.yml
- linchpin/examples/topologies/beaker_server.yml
- linchpin/provision/library/bkr_server.py
- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
This PR adds support for the beaker job whiteboard to beaker topologies, and improves support for the beaker API's `hostRequires` filtering. Docs related to the hostrequires configuration have been added, and I've also updated the beaker examples.
closes #182
closes #196
> whiteboard + hostrequires beaker support, with docs and examples updates

- linchpin/__init__.py
- linchpin/api/__init__.py
- linchpin/provision/roles/common/tasks/main.yml
- linchpin/version.py
Fixes #254 and #159 
The `lp_up()` and `lp_destroy` methods now throw exceptions when invalid data is passed. This allows the command-line interface to catch these exceptions and process them appropriately, usually with a `sys.exit(1)`.
If an error occurs during a playbook run, the return value is passed back from Ansible and assigned to `retval`. The CLI calls sys.exit(retval) appropriately in the `_handle_results` method.
> CLI Error Handling

- docs/source/release/RELEASE_1_0_0.rst
- linchpin/api/__init__.py
Linchpin now handles the return from _invoke_linchpin correctly by providing
a tuple for both ansible.console cases.
> Fixes #263/#267: linchpin destroy after 1.0 upgrade

- linchpin/defaults/schemas/schema_v3.json
- linchpin/defaults/schemas/schema_v4.json
- scripts/create_pypi_package.sh
Fixes #267 
Addresses the credentials compatibility in schema_v4. Since LinchPin has moved away from managing credentials in the topology, and moved it back to the provider's preferred way (with minor exception eg. duffy), credentials is no longer needed in most cases.
If a user would like to use credentials and store them in a central place, the `--creds-path` option can be passed on the command-line.
> Clean up schemas

- linchpin/__init__.py
- linchpin/api/__init__.py
- linchpin/api/context.py
- linchpin/defaults/schemas/schema_v4.json
- linchpin/linchpin.conf
- linchpin/provision/InventoryFilters/GenericInventory.py
- linchpin/provision/InventoryFilters/OpenstackInventory.py
- linchpin/provision/library/auth_driver.py
- linchpin/provision/roles/aws/tasks/provision_resource_group.yml
- linchpin/provision/roles/aws/tasks/teardown_resource_group.yml
- linchpin/provision/roles/common/tasks/load_evars_from_ini.yml
- linchpin/provision/roles/gcloud/tasks/provision_gcloud_gce.yml
- linchpin/provision/roles/gcloud/tasks/provision_resource_group.yml
- linchpin/provision/roles/gcloud/vars/ex_gcloud_creds.yml
- linchpin/provision/roles/inventory_gen/tasks/main.yml
- linchpin/provision/roles/openstack/tasks/main.yml
- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
- linchpin/provision/roles/openstack/tasks/provision_resource_group.yml
- linchpin/provision/roles/output_writer/tasks/main.yml
- linchpin/provision/roles/output_writer/tasks/update_os_server_outputs.yml
- requirements.txt
Fixes #274 
Fixes #275 
For openstack specifically, the default location for clouds.yaml to live is ~/.config/openstack/. A topology would be expressed in this way.
```
---
topology_name: os-test
-
resource_group_name: lp-test
resource_group_type: openstack
- name: resource
type: os_server
flavor: m1.small
image: rhel-7.2-server-x86_64-released
count: 1
keypair: ci-factory
networks:
- atomic-e2e-jenkins-test
fip_pool: 10.8.172.0/22
credentials:
filename: clouds.yaml
profile: ci-osp
```
The clouds.yaml (with --creds-path or not) would look something like so.
```
---
clouds:
default:
auth:
auth_url: http://dashboard.centralci.eng.rdu2.redhat.com:5000/v2.0/
project_name: atomic-e2e-jenkins
username: <redacted>
password: <redacted>
ci-osp:
auth: …
```
> Rework credentials (general) / inventory generation (openstack)

- linchpin/cli/context.py
- linchpin/linchpin.conf
- linchpin/provision/roles/aws/tasks/provision_resource_group.yml
- linchpin/provision/roles/common/tasks/load_evars_from_ini.yml
- linchpin/provision/roles/gcloud/tasks/provision_resource_group.yml
- linchpin/provision/roles/openstack/tasks/provision_resource_group.yml
Fixes #279 
Updated linchpin.conf to have a 'default_credentials_path'
Updated the openstack/aws/gcloud drivers to use 'default_credentials path'
if 'creds_path' isn't provided
Updated load_evars_from_ini to include 'default_credentials_path' in
case ansible-playbook method is used
> Make a default path for credentials

- docs/source/index.rst
- docs/source/topologies_beaker.rst
- linchpin/defaults/schemas/schema_v4.json
- linchpin/provision/library/bkr_server.py
- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
- linchpin/provision/roles/beaker/tasks/teardown_resource_group.yml
- Update docs and v4 schema to match how I actually intended the stuff
to work, as evidenced by the lack of changes to the related bkr_server
logic.
- job_group is no longer a required field when provisioning in beaker.
This was most likely used to get the non-default beaker behavior of
automatic provisioning from a system pool related to a job group
before beaker version 20. This behavior should be explicitly requested
via the "pool" hostrequires tag.
- Added the example topologies to the toplevel index. We've been
building them into the docs but not exposing them to users. If this
was intentional, I'll pull it out.
fixes #278
> Updates to beaker provisioner related to #278

- linchpin/__init__.py
The workspace is set through the following order:
1. by default, LinchpinContext class sets to current directory
2. then if the environment variable WORKSPACE, it replaces the
default
3. last with the most precedence, if the user sets the option
-w or --workspace
There is no need to set the workspace to PWD in case the user has
not set the option or the environment variable because the LinchpinContext
class already sets to os.path.curdir (step 1 above).
> remove redundancy when setting workspace

- linchpin/provision/roles/aws/tasks/main.yml
- linchpin/provision/roles/beaker/tasks/main.yml
- linchpin/provision/roles/duffy/tasks/main.yml
- linchpin/provision/roles/dummy/tasks/main.yml
- linchpin/provision/roles/inventory_gen/tasks/main.yml
- linchpin/provision/roles/output_writer/tasks/main.yml
This commit helps avoid invalid filenames for inventory and resources
output files. The default filename standard uses the topology_name value
(defined inside the topology) file to set the filename. If a user sets
their topology name as the following 'Provision cloud resources'. Their
output file would be 'Provision cloud resources.output', etc. This
patch replaces all spaces with underscores and makes the filename
lowercase.
> Fix the inventory and resources default filenames

- linchpin/__init__.py
- linchpin/api/__init__.py
- linchpin/api/context.py
- linchpin/api/utils.py
- linchpin/cli/__init__.py
Issue #323 indicated that the set_workspace pr #320 broke when the workspace wasn't passed from the command line. This code fixes that issue.
During the work, it was discovered that setting the workspace affected the pinfile, which was done in the init function of runcli. To address this, the lp_init method was added to the LinchpinCli class. Additional code was moved around to accommodate this change.
This fix is more involved than #324, but better addresses the separation of the cli from its python classes. The workspace and pinfile are now set in the cli and api classes for reuse throughout a call.
> set_workspace and pinfile correctly

- linchpin/__init__.py
- linchpin/api/__init__.py
- linchpin/tests/api/test_init_pass.py
This is a patch to issue #306.
I changed return value of run_playbook to a tuple which includes a 'results' dict and return_code to pass into _handle_results().  _handle_results() then calls the sys.exit() with the return_code argument.
> CLI now exits with non-zero exit code on failure

- requirements.txt
Since shade 1.22.2 python-openstackclient, requests, Babel, JsonSchema packages
are inbuilt dependencies, it is not necessary to have those packages in requirements.txt.
> Updated requirements.txt minimizing dependencies

- linchpin/__init__.py
- linchpin/version.py
I think we're ready to release another bugfix version 1.0.3.
Included are the following updates:
* remove gce2 module and use the standard module from ansible
* requirements.txt to use Ansible >= 2.3.1 (this means we can package it for Fedora)
* remove other requirements from requirements.txt that are not necessary
* improved documentation around clouds.yaml and --creds-path
* CLI exits with proper exit codes (with tests to verify)
* linchpin fetch (download local/remote workspaces)
* flake8 testing
* ovirt support with docs!
* linchpin.conf supports overriding specific sections from previous config
* os_server module updated to handle multiple provisioning properly
* remove cruft from api framework
* upgrade setuptools and pip in tests
* move lp_init into api and cli to work together
* …
> Release of v1.0.3

- linchpin/provision/library/bkr_server.py
This bug was introduced in dd1abd2a1fd45078191c5fdca418d66f1b8ec04a as part of the Flake cleanup.
The pull fixes #356.
> Fixed invalid syntax in bkr_server.py introduced by flake8 cleanup & removed unused imports

- linchpin/provision/InventoryFilters/InventoryFilter.py
Currently layout accept only __IP__ magic var inside the vars
section of layout file . Now with this fix users can add their own
custom inventory variables to the hosts.
> bugfix: Added common inventory variables to the inventory layout

- .travis.yml
- linchpin/provision/roles/libvirt/tasks/copy_image_src.yml
Ansible 2.3+ changed the resulting stat object to use mimetype instead
of mime_type. This has now been updated.
Fixes #364
> Libvirt copy_img_src updated stat to use mimetype

- linchpin/api/__init__.py
- linchpin/tests/api/test_init_pass.py
- linchpin/tests/mockdata/contextdata.py
- linchpin/tests/mockdata/dummy/fetch/ws1/localhost
- linchpin/tests/mockdata/dummy/fetch/ws2/localhost
- linchpin/tests/mockdata/dummy/localhost
- linchpin/version.py
This release contains the following:
* Fixed invalid syntax in bkr_server.py introduced by flake8 cleanup
* users can add their own custom inventory variables to the hosts
* Updated schema to support tags in gcloud_gce provisioning
* CODE_OF_CONDUCT.md file now in root of repository
* Libvirt copy_img_src updated stat to use mimetype
* Added optional note about mkvirtualenv in installation document
* Restructured the imports, added ansible runner for ansible 2.4
* Added a Testing section to the CONTRIBUTING document
* Create a localhost file in workspace to accommodate ansible 2.4 warnings
> Move to v1.0.4

- linchpin/defaults/schemas/schema_v4.json
- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
Allows user to specify a specific volume to boot from, which will remain
intact after instance shut down. This volume must be pre-created and
already be flagged as a bootable volume
Allows user to request a new volume be automatically created on boot,
which will then be auto-terminated when the instance is shut down
Lacks the ability to check required/excluded options from schema. That
checking is handled by the Ansible module
> Provide for booting openstack from volume

- .gitignore
- linchpin/__init__.py
- linchpin/api/__init__.py
- linchpin/rundb/__init__.py
- linchpin/rundb/basedb.py
- linchpin/rundb/tinyrundb.py
Linchpin journal provides a bit of data about the previous runs using runDB. This allows a user to see the last X number of components for a specific target. If target data doesn't exist in the runDB, `linchpin journal` will report no data.
> LinchPin Journal

- linchpin/provision/roles/libvirt/templates/libvirt_node.xml.j2
According to https://linuxadmin.io/enable-virsh-console-kvm/
$Subject 
Test by running
```
virsh console <domain_name> 
```
press enter to get into console
> Enabled virsh console on libvirt node

- linchpin/provision/library/rundb.py
- linchpin/provision/roles/common/tasks/initialize_rundb.yml
When running linchpin with ansible-playbook for debugging purposes, it could not run destroy actions because the uhash, and orig_run_id needed to be looked up. Additionally, if the rundb_conn_type value was file, the path is now created if it doesn't exist.
> Allow ansible-playbook to destroy using rundb

- Dockerfiles/Makefile
- Dockerfiles/run_tests.sh
Produces nice test summary
==== TEST summary ====
SUCCESS	fedora27/dummy
SKIPPED	fedora27/duffy
SUCCESS	fedora27/libvirt
SUCCESS	centos7/dummy
SKIPPED	centos7/duffy
SUCCESS	centos7/libvirt
SUCCESS	fedora26/dummy
SKIPPED	fedora26/duffy
SUCCESS	fedora26/libvirt
SUCCESS	fedora25/dummy
SKIPPED	fedora25/duffy
SUCCESS	fedora25/libvirt
FAILURE	centos6/dummy
SKIPPED	centos6/duffy
FAILURE	centos6/libvirt
> restructure to print nice summary of test results

- linchpin/__init__.py
- linchpin/cli/__init__.py
- linchpin/shell/__init__.py
- linchpin/utils/dataparser.py
- linchpin/version.py
- requirements.txt
- setup.py
@jaypoulz pointed out that while Jinja2 template processing was working in a single PinFile, it failed when including the topology or layout files. He suggested LinchPin process those files as well. This PR addresses processing those files as well. Each file gets processed independently using the template-data passed.
Additionally, this output can be written out to a file during to an action 'up' task.
Fixes #428 
Fixes #426
> Allow Jinja2 templating to exist in separate files

- linchpin/api/__init__.py
When using the linchpin API where the workspace != CWD, the provisioning step would fail with the error:
`    [WARNING]: Unable to parse .../localhost as an inventory source.`
This is because the call to ansible_runner in the file **linchpin/aspi/__init__.py** (line 672) was relying on the default inventory_src ('localhost') instead of providing the explicit path. This change adds the inventory_src parameter as a path that matches the localhost path identified/created in lines 501-503 of the **__init__.py** file.
> Fixed failure when workspace != cwd

- Dockerfiles/centos6/Dockerfile
- Dockerfiles/linchpin-test.sh
- Dockerfiles/run_tests.sh
- docs/source/centos6_install.rst
- docs/source/conf.py
- docs/source/configuration.rst
- docs/source/examples/workspace/PinFile.complex.yml
- docs/source/examples/workspace/layouts/duffy.yml
- docs/source/glossary.rst
- docs/source/installation.rst
- docs/source/intro_config.rst
- linchpin/__init__.py
- linchpin/ansible_runner.py
- linchpin/cli/__init__.py
- linchpin/context.py
- linchpin/shell/__init__.py
- linchpin/shell/click_default_group.py
- linchpin/utils/dataparser.py
- linchpin/version.py
- scripts/centos6_install.sh
Fixes in this PR include:
* CentOS 6 Dockerfile test was a bit wonky, so I updated it to work. Fixes #405 
* CentOS 6 also needed some adjustments with jinja2 templating. Addressed this here.
* Removed the python deprecation warnings for now. This is mostly due to CentOS 6 using python2.6.
* Added a bit to the centos6_install.rst document. This should help people install there. Plus, it has a script included that works.
* In the previous PR, the linchpin aliases were removed. I put them back into this one, even though they are likely not used.
* We're using a new workspace (which was actually included in the last PR), but this one fixes up the dummy target so that test will pass again. Also adjusted the linchpin down -> linchpin destroy in the Dockerfiles tests.
> Miscellaneous Fixes and Updates, v1.5.0-rc1 release

- docs/source/examples/workspace/PinFile.jenkins.j2
- docs/source/examples/workspace/topologies/jenkins-slave.j2
- linchpin/provision/beaker.yml
- linchpin/provision/roles/beaker/files/schema.json
Since the Beaker ansible job allows the job_group to be blank, adjusting the schema to match.
Fixed an issue reported by @scoheb around beaker inventory generation. The inventory_gen role had an outdated when statement. This is now updated and should address the issue.
> Minor Beaker fixes

- docs/source/conf.py
Change docs links to point to develop instead of herlo repository. Other minor changes.
> fix example links for documentation

- linchpin/__init__.py
- linchpin/hooks/__init__.py
- linchpin/linchpin.conf
- linchpin/provision/roles/dummy/tasks/provision_res_defs.yml
- linchpin/provision/roles/dummy/tasks/teardown_res_defs.yml
- linchpin/provision/roles/gcloud/tasks/provision_res_defs.yml
- linchpin/provision/roles/inventory_gen/tasks/main.yml
- linchpin/provision/roles/libvirt/files/schema.json
- linchpin/provision/roles/libvirt/tasks/provision_res_defs.yml
- linchpin/provision/roles/openstack/tasks/provision_res_defs.yml
- linchpin/tests/mockdata/dummy/conf/linchpin.conf
Fixes #433 - Moves the rundb into the workspace. The default location is `<workspace>/.rundb/rundb-<macidvalue>.json`
Fixes #434 - Addresses the default value for `enable_uhash`, which is False. Those who wish to have the uhash enabled must turn this on in their configuration file. 
It passes the test [here](https://gitlab.cee.redhat.com/ci-ops/cinch-docs-internal#create-a-jenkins-master-in-openstack-with-vagrant-for-developmenttesting) provided by @robled.
> Optional uhash

- docs/source/aws.rst
- docs/source/examples/workspace/linchpin.conf
- linchpin/__init__.py
- linchpin/cli/__init__.py
- linchpin/provision/roles/aws/tasks/teardown_resource_group.yml
- linchpin/provision/roles/beaker/tasks/teardown_resource_group.yml
When running a destroy, use the existing topology for v1.0.x compatibility
> Run destroy action even if no RunDB records are found

- docs/source/examples/workspace/topologies/bkr-new.yml
- linchpin/__init__.py
- linchpin/provision/library/bkr_info.py
- linchpin/provision/library/bkr_server.py
- linchpin/provision/roles/beaker/files/schema.json
- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
Previously, the bkr_server would receive all provisioning options and
then pass only job IDs through to bkr_server for monitoring, which made
it impossible to pass those options through. It's useful to be able to
pass those through, as that allows for changing things like how long
bkr_info will wait for a provisioning request to succeed or fail.
This also includes a variety of quality of life fixes:
---
closes #424
CentOS-PaaS-SIG#424
Being able to specify `max_attempts` and `attempt_wait_time` in the
topology allows you to effectively specify the timeout, where `timeout =
max_attempts * attempt_wait_time`.
---
closes #399
CentOS-PaaS-SIG#399
In addition to the job IDs, job URLs are now also printed out in the
course of provisioning. This debug print happens between the bkr_server …
> Allow passing provisioning options through to bkr_info

- config/README.rst
- linchpin/version.py
Interim version for beaker fix at request of ci-central-qe. 
* The `__short_version__` variable will stay at 1.5.1 since documentation will get updated in v1.5.2, not here.
* Fixed spelling errors in config/README.rst
> Update to 1.5.1.1

- linchpin/__init__.py
- linchpin/shell/__init__.py
Fixes #420 
The `linchpin journal` command now supports an optional target. If target(s) are not provided, linchpin will print to STDERR, the journal for all available targets.
```
$ linchpin journal
Target: os-vol-new
run_id	    action	     uhash	        rc	
--------------------------------------------------
9      	       up	     f641	        0	
8      	  destroy	     763a	        0	
7      	  destroy	     763a	        0	
Target: ansible-playbook
run_id	    action	     uhash	        rc	
--------------------------------------------------
10     	       up	     f99b	        0	
9      	       up	     bce6	        0	
8      	       up	         	        0	
Target: bkr
run_id	    action	     uhash	        rc	
--------------------------------------------------
35     	       up	     41bc …
```
> Enable linchpin journal without target

- linchpin/provision/roles/beaker/files/schema.json
Turns out that bkr_server already had support for task params, we just
need to allow it in recipes; all other machinery is in place.
To add a custom reservesys time, add this to a recipe inside recipesets,
in the same place as things like hostrequires, distro, etc.
```yaml
taskparam:
- RESERVETIME=7200
```
Value is in seconds, so this is a 2-hour reservation.
closes: https://github.com/CentOS-PaaS-SIG/linchpin/issues/380
> Add taskparam support to beaker schema

- docs/source/aws.rst
- linchpin/provision/roles/aws/files/schema.json
- linchpin/provision/roles/aws/tasks/teardown_resource_group.yml
* Fixed references in AWS docs from OpenStack -> AWS
* Added a way to set up credentials in the AWS docs
* Added 'vpc_subnet_id' to topology schema for VPC to resolve VPC issues
(#484)
* Fixed an attribute name used for teardown of AWS resources (#484)
> AWS VPC and docs fixes (#484)

- docs/source/aws.rst
- docs/source/examples/workspace/topologies/aws-ec2-vpc.yml
- linchpin/provision/InventoryFilters/AWSInventory.py
- linchpin/provision/roles/aws/files/schema.json
* Added 'assign_public_ip' to schema and EC2 topology example (#489)
* Added 'vpc_subnet_id' to EC2 topology example
* Fixed AWS EC2 inventory file generation, added support for public vs
private instances for the inventory, and updated sphinx docs with an
explanation of how the inventory files are generated (#490)
* Fixed a formatting warning from the sphinx 'make html' command for the
Environment Variables and Provisioning section of the AWS sphinx docs.
> AWS EC2 provider networking and inventory generation fixes

- linchpin/provision/library/bkr_server.py
- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
This tweaks some already duplicated code in bkr_server to provide
outputs that match the same format as bkr_info, which lets us store
usable topology information in the rundb immediately after creating
beaker jobs. This makes "linchpin destroy" still work even if later
beaker provisioning steps fail, when using rundb.
closes https://github.com/CentOS-PaaS-SIG/linchpin/issues/471
> Stash beaker job info in rundb immediately

- .gitignore
- config/Dockerfiles/Jenkinsfile
- config/Dockerfiles/linchpin-install.sh
- config/Dockerfiles/linchpin-tests.sh
- config/Dockerfiles/run_tests.sh
This makes it much more generic to support drivers that need
authentication passed in.
Support is there for testing aws but the credential code needs to be
fixed first.
This may break duffy testing if the same CREDS_PATH issue is present in the duffy driver.
> rework how credentials are used.

- docs/source/openstack.rst
- linchpin/provision/roles/openstack/files/schema.json
- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
Updated the schema.json and playbooks for OpenStack to support list of pre-provisioned volumes
names as a list of attachments to provisioned instances. No new changes were added to os_server2
module since attaching volumes is already supported.
fixes #479
> Added support for attaching volumes to provisioned instances.

- config/s2i/jenkins/master/configuration/init.groovy
Get current security context instead of creating a new one.
> Fix jenkins security

- linchpin/__init__.py
- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
- linchpin/version.py
Per an email with @beerparty, I've updated the os_server timeout to 1200 seconds (20 minutes) as a semi-mitigation. Fixed a small amount of documentation. Updated to v1.5.2 in preparation for release today.
> Fixes before v1.5.2 release

- config/Dockerfiles/Jenkinsfile
- config/Dockerfiles/JenkinsfileContainer
- config/Dockerfiles/JenkinsfileGHPRMerge
- config/Dockerfiles/JenkinsfileGHPRTrigger
- config/Dockerfiles/JenkinsfileMergePR
- config/Dockerfiles/JenkinsfileMessageBusMerge
- config/Dockerfiles/JenkinsfileMessageBusTrigger
- config/s2i/jenkins/jenkins-continuous-infra-slave-buildconfig-template.yaml
- config/s2i/jenkins/slave/Dockerfile
Two types of triggers now:
- GHPRB : Git Hub PR Builder
- MessageBus: Allows for downstream behind firewalls
The GHPRB trigger sends a message on the bus that will
trigger the messagebus job.
Please let me merge this after review - I will need to update the jobs on centos ci since things have been renamed.
> Split triggers into their own jobs

- config/Dockerfiles/linchpin-tests.sh
- linchpin/provision/roles/aws/tasks/provision_aws_cfn.yml
- linchpin/provision/roles/aws/tasks/provision_aws_ec2.yml
- linchpin/provision/roles/aws/tasks/teardown_aws_cfn.yml
- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
- linchpin/provision/roles/openstack/tasks/provision_os_heat.yml
rhel/centos 7 has an older version of jinja2 which doesn't include equalto.
> use match instead of equalto.

- .travis.yml
- requirements.txt
- setup.cfg
- setup.py
jsonschema is no longer required ( schemacheck ansible module still needs to be removed)
pytest finds and performs tests, updated this in the .travis.yml as well.
testing shade 1.18 for compatibility with F27 distro packaging (EPEL doesn't have shade at all, only pip)
> Use pytest on travis

- docs/source/examples/workspace/linchpin.conf
- docs/source/examples/workspace/topologies/bkr-new.yml
- linchpin/cli/__init__.py
- linchpin/linchpin.constants
- linchpin/provision/roles/beaker/files/schema.json
- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
- linchpin/tests/mockdata/dummy/linchpin.conf
- linchpin/version.py
Per #542, the name field should be available in topologies for bkr_server, os_server, and aws_ec2 roles/resources. In turn, this name data will now be distilled (if used) into the context printed at the end of each run.
The majority of the work was done in the beaker provision_resource_group.yml playbook, which involved merging the bkr_id values, the bkr_host values, and the bkr_name values into the output to ensure easy distillation.
Additionally, this PR addresses #531 by adding a new flag option (distill_on_error) to the linchpin.conf enabling distilled data to write out any successfully provisioned resources, even if some fail.
> Name in topology, distilled data

- config/Dockerfiles/JenkinsfileContainer
- src/org/centos/pipeline/LinchpinPipelineUtils.groovy
- don't break out of the target selection routine when you get a match.
This allows multiple targets to match for the same file.
- Change the dummy regex to match all files except linchpin/version.py
This means we will only test the dummy target for non-target specific
changes.  But if the linchpin/version.py file is changed we will test
every target.  This is a good compromise for speed for every PR
and completeness when doing a release.
> This changes the selective target testing logic slightly.

- .gitignore
- MANIFEST.in
- linchpin/version.py
- scripts/create_pypi_package.sh
After releasing v1.5.3a1, I noticed that items in docs/source/examples/workspace/inventories/ were being packaged up even though that data is from specific runs of linchpin during testing.
This new create_pypi_package.sh checks out from git.
The requirements are that the tags be pushed to upstream prior to running this command. If not, the creation of packages will fail.
> Remove CRUFTY bits and use git for pypi packages

- linchpin/ansible_runner.py
- linchpin/callbacks.py
- requirements.txt
PlaybookCallback defined does not have attribute _loader_name which is
required by the ansible executor.py is added in constructor before the
super call. Further, reverted ansible version in requirements.txt
back to >=2.3.1.
Fixes #564 #563
> Bugfix: Making linchpin work with Ansible 2.5.x

- linchpin/provision/InventoryFilters/InventoryFilter.py
Currently, The latest provisioned first is chosen in to inventory according
to the layout rules. However this needs to change because when using
multiple resource definitions the order does not comply to layout
refer issue #540 for more details. Current commit fixes #540
> bugfix: Change the order of picking hosts from resources to Inventory

- docs/source/examples/workspace/linchpin.conf
- linchpin/cli/__init__.py
- linchpin/linchpin.constants
- linchpin/shell/__init__.py
Returns 0 even if one target provision is successfull when
distill_on_error = True
Returns rc > 0 even if one target provision fails when
distill_on_error = False
> Return the rc's based on config varible distill_on_error

- config/Dockerfiles/linchpin-test.sh
- config/Dockerfiles/linchpin-tests.sh
- docs/source/examples/workspace/topologies/os-sg-new.yml
- linchpin/cli/__init__.py
- linchpin/provision/roles/openstack/tasks/provision_os_sg.yml
The code below should continue to run all tests as normal. But the os-sg-new test, which creates an openstack security group will have the distro prepended to the name of the security group. This should help with the race condition discovered in [#571#issuecomment-387111515](https://github.com/CentOS-PaaS-SIG/linchpin/pull/571#issuecomment-387111515) when running all distros in parallel.
There was also a small bug fixed in the linchpin cli code which was not passing the template-data to all components of the PinFile structure.
> Openstack Security Group testing fix

- linchpin/cli/__init__.py
During the rework of the context distiller, the code for the --output-pinfile option was inadvertently removed. This patch puts the functionality back in place.
> Reinstate --output-pinfile

- linchpin/cli/__init__.py
- linchpin/utils/dataparser.py
Adjusted the dataparser.process function to treat all data as a potential file. It checks now for a leading '@' and reads the file into data before continuing. The inventory_layout templating was failing because it wasn't passing any values along.
Fixes #584
> Fix layout templating

- linchpin/cli/__init__.py
It seems that in 1.5.3, the pf_data somehow changed back from self.pf_data. This adjusts that back so pf_data (template data) will be propagated and processed through to both the topology and inventory_layout.
> Fix parsing regression for layouts and topologies

- docs/source/examples/workspace/topologies/libvirt-el7net.yml
- docs/source/libvirt.rst
- linchpin/provision/roles/libvirt/files/schema.json
- linchpin/provision/roles/libvirt/templates/libvirt_network.xml.j2
There are some caveats to this.
- Currently additional networks only works if cloud-config is not used. (This is not new but it was not clear to me, so it might not be clear to others)
- You will need to use virt-customize on the image to set the hostname.  The default hostname of localhost will not update dns records.
A future RFE would be to drop the requirement on virt-install and try to integrate virt-customize.
fixes #543
> Add support for domain specification in dnsmasq

- linchpin/provision/roles/ovirt/tasks/provision_resource_group.yml
Quick fix removing ')'
```
TASK [ovirt : Provisioning resource definitions of current group]
***********************************************
task path:
/home/user/venv/lib/python2.7/site-packages/linchpin/provision/roles/ovirt/tasks/provision_resource_gr
yml:33
fatal: [localhost]: FAILED! => {
"msg": "template error while templating string: unexpected ')'.
String: {{ res_grp['resource_definitions']) }
}
```
> Fixes ovirt role template error

- MANIFEST.in
- linchpin/version.py
- setup.py
I discovered tests were not being included in the linchpin releases. To do verification of a release, the package will run the test suite, along with some integration (and maybe regression one day) tests. Without this update, that cannot happen.
Because I was already modifying the MANIFEST.in anyway, I went ahead and fine tuned the files to be included in the package.
> A more specific MANIFEST.in and setup.py

- linchpin/provision/roles/beaker/files/schema.json
While trying to provision a resource in beaker using the restraint harness I found that linchpin doesn't accept the ks_meta param in topology.
> ks_meta in recipesets is valid schema.

- config/Dockerfiles/centos7/Dockerfile
- config/Dockerfiles/centos7/centos7-pike.repo
The CentOS7 container would not succecssfully build the linchpin executable after some sort of change recently. This update uses custom built rpms from a COPR repository, along with a CentOS7 (openstack-pike) repository to get linchpin to install again.
The reason this is a problem is that pip will not uninstall certain distutils packages (the above named are the ones dealt with here) using pip. RPM dependencies cause things to be uninstalled which are needed, and CentOS7 core doesn't have new enough RPMs.
> Replace PyYAML, python-requests, python-ipaddress with RPMs (centos7)

- linchpin/provision/roles/ovirt/files/schema.json
- linchpin/provision/roles/ovirt/tasks/provision_ovirt_vms.yml
- linchpin/provision/roles/ovirt/tasks/provision_res_defs.yml
- `res_def['res_name']` does not exist.  Modified to use `res_def['name']`.
- Added `count` parameter
- Added creation of disks
- Added do-until for the guest agent to provide an IPv4 address which is used in inventory.
Topology Example:
```
---
topology_name: kubevirt_cluster
- resource_group_name: ovirt
resource_group_type: ovirt
- name: master
template: centos
cluster: Default
role: ovirt_vms
count: 1
disks:
- name: docker
size: 1GiB
format: cow
interface: virtio_scsi
storage_domain: n1-virtomation-com-Local
- name: gluster
size: 1GiB
format: cow
interface: virtio_scsi
storage_domain: n1-virtomation-com-Local
- name: node
template: centos
cluster: Default
role: ovirt_vms
count: 2
credentials:
filename: ovirt_creds.yml
profile: ovirt
```
cc: …
> Fix ovirt provider; Add count, disk provisioning and network delay

- linchpin/hooks/__init__.py
I was trying to invoke linchpin by a sample API script 
```python
import linchpin
from linchpin import LinchpinAPI
from linchpin.context import LinchpinContext 
import yaml
pinfile = """
---
dummy_target:
topology:
topology_name: "dummy"
- resource_group_name: "dummy"
resource_group_type: "dummy"
- role: "dummy_node"
name: "web"
count: 1
layout:
inventory_layout:
vars:
hostname: __IP__
hosts:
example-node:
count: 1
host_groups:
- example
"""
pinfile = yaml.load(pinfile)
ctx = LinchpinContext()
ctx.console = True
ctx.setup_logging()
ctx.evars = {}
workspace_path = "/home/srallaba/workspace/lp_ws/ex_hooks/workspace"
ctx.set_evar("workspace", workspace_path)
lp_obj = LinchpinAPI(ctx)
lp_obj.workspace = workspace_path
lp_obj.do_action(pinfile)
```
while …
> bugfix to make LinchpinAPI work standalone

- docs/source/advanced/validator.rst
- linchpin/__init__.py
- linchpin/cli/__init__.py
- linchpin/exceptions/__init__.py
- linchpin/provision/roles/libvirt/files/schema.json
- linchpin/provision/roles/ovirt/files/schema.json
- linchpin/shell/__init__.py
- linchpin/utils/validator.py
- requirements.txt
`linchpin validate` validates topologies and provides a list of errors if the topology does not successfully validate.  This PR also fixes some schema errors that prevent validation and updates cerberus to version 1.2, which is required in order to validate lists inside of schemas.
> Add linchpin validate command

- config/Dockerfiles/tests.d/libvirt/01_temp_general
- docs/source/examples/workspace/topologies/libvirt-new.yml
- linchpin/InventoryFilters/GenericInventory.py
- linchpin/provision/roles/libvirt/files/schema.json
- linchpin/provision/roles/libvirt/templates/cloud-config/user-data
- linchpin/provision/roles/libvirt/templates/cloud-config/user-data-fixed
- linchpin/provision/roles/libvirt/templates/cloud-config/user-data-fixed-local
- linchpin/provision/roles/libvirt/templates/cloud-config/user-data-fixed-remote
- linchpin/provision/roles/libvirt/templates/cloud-config/user-data-local
- linchpin/provision/roles/libvirt/templates/cloud-config/user-data-remote
The new validation structures require a dict for this schema instead of just a list. Cerberus 1.2 is a bit more strict about these things.
The rest of the updates were to match the [cloud_config documentation](https://cloudinit.readthedocs.io/en/latest/topics/examples.html#including-users-and-groups) for users and groups.
> Schema update to libvirt cloud_config

- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
- linchpin/provision/roles/openstack/tasks/provision_resource_group.yml
During the openstack playbooks, the plays were checking for an undefined
auth_var, but `auth_var = ""` by default.
Adjusted the tests to verify the `auth_var` was indeed empty, rather than undefined.
Fixes #682
> The auth_var is never undefined, change conditional tests

- docs/source/examples/workspace/linchpin.conf
- linchpin/cli/__init__.py
- linchpin/linchpin.constants
Updated linchpin inventory generation to use relative/absolute paths if mentioned in layoutfile 
fixes #617 
Example workspace demonstrating the same:
https://github.com/samvarankashyap/linchpin_dummy_ws_demo_rel_path
> Updated linchpin inventory generation to use relative/absolute paths

- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
When uri_hostname != localhost we should read the ip address from the
registered variable extract_ip_address_result_remote and not
extract_ip_address_result.
> Libvirt: Read ip address from correct registered variable

- docs/source/advanced_topics.rst
Fixes #676 
@14rcole, adding the above reference will automatically close the related ticket when this is merged. :smile:
> Remove linchpin validate from advanced topics

- linchpin/__init__.py
If topology does not validate, the `linchpin up` output telling the user to run `linchpin validate` had some spelling errors
> Fix spelling errors in linchpin up output

- docs/source/examples/workspaces/aws/PinFile
This was causing some strange validation errors due to the indentation problems
> Fix indentation of aws-sg-new target

- linchpin/__init__.py
- linchpin/shell/__init__.py
- linchpin/tests/test_init_pass.py
Make _validate_topology and _validate_layout public so that they can be used via linchpin as an API.  Dependent of #662
> Make validation functions public

- docs/source/examples/workspaces/duffy/PinFile
The indentation of the workspaces/duffy PinFile was incorrect, and the credentials file could not be found as a result
> Fix workspaces/duffy PinFile

- linchpin/provision/roles/aws/tasks/teardown_resource_group.yml
A variable in teardown_resource_group was being set to some_dict['content']['aws_ec2_res'][0], then later on, ansible would attempt to read variable['aws_ec2_res'].  I changed the variable to be equal to some_dict['content'], but if it's better practice to change the way the variable is being read later on, I can do that instead
> Fix error with aws teardown

- linchpin/__init__.py
- linchpin/shell/__init__.py
If a layout and topology exist for a given schema, linchpin would prepend the message with [ERROR] instead of [SUCCESS].  This PR fixes that
> Make linchpin validate stop printing [ERROR] on success

- docs/source/examples/workspace/topologies/openshift-new.yml
- docs/source/examples/workspaces/openshift/PinFile
- docs/source/openshift.rst
- linchpin/provision/roles/openshift/tasks/provision_res_defs.yml
- linchpin/provision/roles/openshift/tasks/provision_resource_group.yml
Fixes: #675 
Updates the openshift role to read from both creds path and inline credentials 
openshift credential format is as follows:
```yaml
test:
api_endpoint: profileexample.com:8443/
api_token: thisisfromprofile
default:
api_endpoint: profileexample.com:8443/
api_token: thisisfromprofile
```
Update topology:
```yaml
---
topology_name: "dummy"
- resource_group_name: simple
resource_group_type: openshift
- name: openshift
role: openshift_inline
data:
- apiVersion: v1
kind: ReplicationController
metadata:
name: jenkins-slave
namespace: central-ci-test-ghelling
spec:
replicas: 1
selector:
name: jenkins-slave
template:
metadata:
labels:
name: jenkins-slave
spec:
containers:
- image: redhatqecinch/jenkins_slave:latest
name: jenkins-slave
env:
- name: …
```
> Update openshift role to fetch creds from --creds-path

- docs/source/examples/workspaces/linchpin.conf
- linchpin/fetch/fetch_git.py
- linchpin/linchpin.constants
- linchpin/shell/__init__.py
For the purposes of documenting the new tutorial, I wanted to use linchpin init with some specific arguments. In this case, it was easier to modify `linchpin init` to allow it to use `lp_fetch()` to clone the git repository and use the workspaces that already exist there.
The `linchpin init` command will create a subdirectory, clone this repository (master branch by default) and copy the appropriate workspace to the subdirectory.
This PR allows a user to do the following:
```
[/tmp]$ linchpin init
Created destination workspace: /tmp/dummy
[/tmp]$ ls dummy
PinFile  PinFile.json  README.rst
[/tmp]$ cat dummy/PinFile
$ cat dummy/PinFile
---
dummy-new:
topology:
topology_name: "dummy_cluster" # topology name
- resource_group_name: "dummy"
resource_group_type: "dummy" …
```
> Make 'linchpin init' use 'linchpin fetch'

- docs/source/examples/workspaces/dummy/PinFile
- docs/source/simple_pinfile.rst
- docs/source/simple_up.rst
- docs/source/simple_workspace.rst
An update to the new getting started guide. Fixes some typos, adds a couple of more examples and clarifies a few things.
After checking it out, go to the `docs` directory and run `make html`. Then open the `docs/build/html/index.html` in a browser and view the 'Getting Started` section.
> Fix Typos in Getting Started Docs

- linchpin/shell/__init__.py
Code typo made linchpin validate print only "topology valid" if both topology and layout for a given host were valid.  This fixes that bug
> Make linchpin validate print both layout and topology success

- linchpin/provision/library/openshift.py
Sets the namespace variable to "" when None
fixes : #771
> bugfix: Set namespace default to null string 

- config/Dockerfiles/Jenkinsfile
- config/Dockerfiles/JenkinsfileContainer
- src/org/centos/pipeline/LinchpinPipelineUtils.groovy
Introduce __RELEASE__ provider which will match on linchpin/version.py
change.  dummy still matches everything and all drivers will still
match if linchpin/version.py changes.  This just makes it so you
can do testing *ONLY* when it's a release.
> Allow for easy release testing

- linchpin/provision/filter_plugins/combine_hosts_names.py
Previously, each name was combined with each host.  This fixes the function so that each name is paired with the corresponding host
> Fix combination beaker names and hosts

- linchpin/provision/library/dummy.py
- linchpin/provision/roles/dummy/files/schema.json
- linchpin/provision/roles/dummy/tasks/provision_res_defs.yml
POC w.r.to : #738 
Introduces domain parameter 
Further , eliminates the count appending to instance name when running for single instance
with uhash=False in linchpin.conf
Example workspace:
https://github.com/samvarankashyap/linchpin_dummy_domain
> [POC]: Introducing Dummy domain as a parameter to generate fake inventories

- docs/source/installation.rst
- linchpin/__init__.py
- linchpin/cli/__init__.py
- linchpin/provision/ask_sudo_setup.yml
- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
- linchpin/provision/roles/dependencies/tasks/beaker_deps.yml
- linchpin/provision/roles/dependencies/tasks/docs_deps.yml
- linchpin/provision/roles/dependencies/tasks/libvirt_deps.yml
- linchpin/provision/roles/dependencies/tasks/main.yml
- linchpin/provision/roles/dependencies/tasks/setup_dnf_deps.yml
- linchpin/provision/roles/dependencies/tasks/setup_selinux_deps.yml
- linchpin/provision/roles/dependencies/tasks/test_deps.yml
- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
- linchpin/provision/roles/libvirt/tasks/virt_customize.yml
- linchpin/provision/setup.yml
- linchpin/shell/__init__.py
Introducing linchpin setup command which are used to automate linchpin external dependency installations 
command: 
```
linchpin setup [dependency_list]
```
example usage: 
```
linchpin setup
```
```
linchpin setup beaker libvirt
```
Further current PR adds debug fail messages to beaker and libvirt when something goes wrong with the provisioning process. It works both in virtualenv.
Some of the dependencies might need  sudo permissions which can either be done using 
```
linchpin setup --ask-sudo-pass 
```
or running linchpin with sudo 
```
sudo linchpin setup
```
or running linchpin under a privileged sudo user 
```
linchpin setup
```
fixes: #419
> Linchpin setup and Adding error handling messages beaker and libvirt

- linchpin/fetch/fetch_git.py
fixes: #835 
The above can also be avoided by updating git version >= 1.8.5
> Use change directory to maintain backward compatibility with git versions <1.8.5

- config/Dockerfiles/JenkinsfileGHPRMerge
This library method gives us the merge commit so we can pass that to the next job.
Tested this locally and it works with the latest updates to contra-lib
> use gitHubAPI to do the merge

- config/Dockerfiles/tests.d/openstack/07_os-router
- docs/source/examples/workspaces/openstack/PinFile
- docs/source/examples/workspaces/openstack/topologies/os-router.yml
- docs/source/openstack.rst
- linchpin/provision/roles/openstack/files/schema.json
- linchpin/provision/roles/openstack/tasks/provision_os_router.yml
Summary:
- Updated examples and documentation for os_router role
- Added test for os_router
- Updated playbooks to support os_router ansible module
- Updated schema to support os_router module
fixes #819
> Add support to os_router in linchpin topologies

- linchpin/__init__.py
- linchpin/context.py
- linchpin/fetch/__init__.py
- linchpin/fetch/fetch_git.py
- linchpin/fetch/fetch_http.py
- linchpin/tests/InventoryFilters/test_CFGInventoryFormatter_pass.py
- linchpin/tests/InventoryFilters/test_GenericInventory_pass.py
- linchpin/tests/InventoryFilters/test_InventoryFilter_pass.py
- linchpin/tests/InventoryFilters/test_JSONInventoryFormatter_pass.py
- linchpin/tests/cli/test_context_pass.py
- linchpin/tests/mockdata/contextdata.py
Python has long supported explicit relative imports and encouarged them
in the style guide. However, in the days of Python 3, this is now a
requirement of the language. This syntax still works in Python 2.
Addresses #853
> Force relative imports to be explicit

- config/Dockerfiles/tests.d/openstack/08_os_subnet
- docs/source/examples/workspaces/openstack/PinFile
- docs/source/examples/workspaces/openstack/topologies/os-subnet.yml
- docs/source/openstack.rst
- linchpin/provision/roles/openstack/files/schema.json
- linchpin/provision/roles/openstack/tasks/provision_os_subnet.yml
Summary:
- Updated examples and documentation for os_subnet role
- Added test for os_subnet
- Updated playbooks to support os_subnet ansible module
- Updated schema to support os_subnet module
fixes #820
> Add support for os_subnet role in linchpin topologies

- linchpin/provision/roles/openstack/files/schema.json
The `unique` field, which exists for all other openstack resources, was omitted from the os_network schema.  Adding this back in fixes the validation error preventing upshift tests in #866 from passing
> Add 'unique' field to os_network

- linchpin/cli/__init__.py
- linchpin/provision/roles/common/files/topo-schema.json
- linchpin/validator/__init__.py
Topology validation only considers resource groups, which are provider-specific.  This validates the general components of the topology as well
> Validate high-level components of topologies

- linchpin/hooks/__init__.py
- linchpin/hooks/action_managers/subprocess_action_manager.py
Shell hook context was postfixed to the command, which would cause context to be interpreted as arguments to the command. This prefixes the context so that the context can be used as variables in the command and is not interpreted as a set of arguments
There needs to be an integration test that runs shell hooks (we currently only have ansible hooks).  I'm working on it, but I need to submit another bug fix related to shell hooks first so I'll include it in that.
> Reorder shell hook command

- linchpin/provision/roles/gather_resources/tasks/update_async_outputs.yml
Remove the above dependency from the playbooks, as the file no longer exists.  Also gets rid of a long warning that prints every time linchpin is run
> Remove import of update_aws_cfn_outputs.yml

- linchpin/__init__.py
This prevents users from having to reprovision with a higher verbosity on failure. Fulfills #867
> Make linchpin print provision error when verbosity=0

- config/Dockerfiles/tests.d/aws/01_aws_ec2_eip
- docs/source/aws.rst
- docs/source/examples/workspace/topologies/aws-ec2-eip.yml
- docs/source/examples/workspaces/aws/PinFile
- docs/source/examples/workspaces/aws/topologies/aws-ec2-eip.yml
- linchpin/provision/roles/aws/files/schema.json
- linchpin/provision/roles/aws/tasks/main.yml
- linchpin/provision/roles/aws/tasks/provision_aws_ec2_eip.yml
- linchpin/provision/roles/aws/tasks/teardown_aws_ec2_eip.yml
- linchpin/provision/roles/aws/tasks/teardown_resource_group.yml
$subject
Fixes #825 
Example:
```
aws-ec2-eip:
topology:
topology_name: ec2-new
- resource_group_name: "aws"
resource_group_type: "aws"
- name: demoday
role: aws_ec2_eip
region: us-east-1
credentials:
filename: aws.key
profile: default
```
> Add support for aws_ec2_eip module

- config/Dockerfiles/tests.d/aws/01_aws_ec2_eip
- config/Dockerfiles/tests.d/aws/02_aws_ec2_vpc_net
- config/Dockerfiles/tests.d/aws/03_aws_ec2_vpc_subnet
- docs/source/aws.rst
- docs/source/examples/workspace/topologies/aws-ec2-vpc-subnet.yml
- docs/source/examples/workspaces/aws/PinFile
- linchpin/provision/filter_plugins/fetch_attr.py
- linchpin/provision/roles/aws/files/schema.json
- linchpin/provision/roles/aws/tasks/provision_aws_ec2_vpc_net.yml
- linchpin/provision/roles/aws/tasks/provision_aws_ec2_vpc_subnet.yml
- linchpin/provision/roles/aws/tasks/teardown_aws_ec2_vpc_subnet.yml
- linchpin/provision/roles/aws/tasks/teardown_resource_group.yml
fixes: #911 
example:
```yaml
aws-ec2-vpc-subnet:
topology:
topology_name: ec2vpcsubnetdemo
- resource_group_name: "awsvpcsubnet"
resource_group_type: "aws"
- name: demovpcnetsubnet
role: aws_ec2_vpc_net
region: us-east-1
cidr_block: 13.0.0.0/16
tags:
module: aws_ec2_vpc_net
this: alsoworks
tenancy: dedicated
- name: demodayvpcsubnet
role: aws_ec2_vpc_subnet
region: us-east-1
cidr_block: 13.0.1.0/24 
tags:
module: aws_ec2_vpc_net
this: alsoworks
tenancy: dedicated
credentials:
filename: aws.key
profile: default
```
To be merged after #894 #907  to avoid merge conflicts
> Add support to aws ec2 vpc subnet module

- config/Dockerfiles/tests.d/aws/01_aws_ec2_eip
- config/Dockerfiles/tests.d/aws/02_aws_ec2_vpc_net
- config/Dockerfiles/tests.d/aws/03_aws_ec2_vpc_subnet
- config/Dockerfiles/tests.d/aws/04_aws_ec2_vpc_routetable
- docs/source/aws.rst
- docs/source/examples/workspace/topologies/aws-ec2-vpc-subnet.yml
- docs/source/examples/workspaces/aws/PinFile
- docs/source/examples/workspaces/aws/topologies/aws-ec2-vpc-routetable.yml
- linchpin/provision/filter_plugins/fetch_attr.py
- linchpin/provision/roles/aws/files/schema.json
- linchpin/provision/roles/aws/tasks/provision_aws_ec2_vpc_net.yml
- linchpin/provision/roles/aws/tasks/provision_aws_ec2_vpc_routetable.yml
- linchpin/provision/roles/aws/tasks/provision_aws_ec2_vpc_subnet.yml
- linchpin/provision/roles/aws/tasks/teardown_aws_ec2_vpc_routetable.yml
- linchpin/provision/roles/aws/tasks/teardown_aws_ec2_vpc_subnet.yml
- linchpin/provision/roles/aws/tasks/teardown_resource_group.yml
$subject
To be merged after #911 
fixes: #913 
example:
```yaml
region: us-east-1
cidr_block: 15.0.0.0/16
tags:
module: aws_ec2_vpc_net
this: alsoworks
tenancy: dedicated
- name: demo_vpc_subnet_r
role: aws_ec2_vpc_subnet
region: us-east-1
vpc_name: demo_vpc_net_r
cidr: 15.0.1.0/24
tags:
module: aws_ec2_vpc_subnet
this: alsoworks
- name: demo_routetable
role: aws_ec2_vpc_routetable
region: us-east-1
vpc_name: demo_vpc_net_r
tags:
module: aws_ec2_vpc_routetable
this: alsoworks
subnets:
- 'demo_vpc_subnet_r'
credentials:
filename: aws.yaml
profile: default
```
> Add support to aws_ec2_vpc_routetable

- linchpin/provision/library/bkr_server.py
Currently, when the system is reserved through the task /distribution/reservesys (which is the case by default) reserve_duration has no effect.
> Apply reserve_duration time to /distribution/reservesys task

- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
Fixed typo in tasks/provision_resource_group.yml
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>
> beaker: fix typo s/beacuse/because/

- config/Dockerfiles/tests.d/beaker/03_beaker_inventory
- docs/source/examples/workspaces/beaker/PinFile
Tests for this will fail until #926 is merged.  This is the integration test corresponding to #909.  I can modify it so that it passes without #926 if necessary but it'll be sloppy
> Add integration test to check for correct number of hosts in beaker

- config/Dockerfiles/JenkinsfileContainer
- linchpin/provision/library/bkr_info.py
Currently the Beaker job with multiple reservation recipes,
in case at least one return Canceled/Aborted/Warn status then
Linchpin exits with error. But the Beaker job is not canceled,
as a result the remaining recipes may end up reserving resources
which likely won't be used.
Changed the bkr_info role to cancel the job if any recipe
return Canceled/Aborted/Warn status.
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>
> Nicely cancel Beaker jobs on error

- linchpin/provision/roles/gather_resources/tasks/wait_on_os_server.yml
- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
os_server async provisioning retained the wrong data in the resources section of the rundb, and thus instances could not be destroyed.  Also, inventories could not be written correctly
fixes #932
> Fix os_server async provisioning

- config/Dockerfiles/Jenkinsfile
I have a bad feeling that running two containers with systemd
causes data to be leaked between them.  Possibly via /proc/mounts.
> Experiment to run one systemd container

- linchpin/provision/roles/libvirt/files/schema.json
Though we have support in jinja network template the forward_mode is not enabled in topology
fixes: #941
> Enable forward_mode for libvirt network

- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
$subject
This commit needs to be revisited when there are multiple external networks are
attached to the virtual machines.
fixes #942
> Updated task to use first found mac address when multiple networks are involved

- docs/source/beaker.rst
- linchpin/provision/library/bkr_server.py
- linchpin/provision/roles/beaker/files/schema.json
- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
Linchpin provides the ssh_key property which allows to set (statically)
ssh key's content. However one may want to use a dynamically generated
key file, and that's what is solved on this change.
It was introduced the ssh_key_file property for recipesets, that you can set
a list of file names from where read the ssh public key. For example:
... snip ...
recipesets:
- family: RedHatEnterpriseLinux8
name: rhel80-x86_64
arch: x86_64
variant: BaseOS
count: 1
ssh_key_file:
- ssh_key.pub
hostrequires:
.. snip ..
The key files should be stored on the Linchpin's credentials directory, or
on alternative location and the ssh_keys_path property for resource_definitions
should be set accordingly.
> Intro ssh_key_file property on Beaker's topology

- linchpin/provision/filter_plugins/get_libvirt_files.py
This change allows linchpin destroy on a libvirt provider to complete when no VMs are defined.
Fixes #967
> Allow libvirt destroy when no VMs are defined

- linchpin/provision/roles/libvirt/tasks/copy_image_src.yml
- linchpin/provision/roles/libvirt/tasks/copy_image_src_local.yml
- linchpin/provision/roles/libvirt/tasks/copy_image_src_remote.yml
- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
- linchpin/provision/roles/libvirt/tasks/teardown_libvirt_node.yml
- linchpin/provision/roles/libvirt/tasks/virt_customize.yml
This change implements the following changes:
- register res_count var as a list by using with_sequence. Previously
the res_count var was registered as a shell task output which made
res_count.stdout a string and didn't allow iterating over the items
in the list.
- store output_name var as a list allowing iteration over multiple
elements. Previously only the last iteration item was stored in the
output_name.
> Fix issue #960

- config/Dockerfiles/tests.d/libvirt/03_libvirt-network
- docs/source/examples/workspaces/libvirt/PinFile
- linchpin/provision/roles/libvirt/files/schema.json
- linchpin/provision/roles/libvirt/templates/libvirt_network.xml.j2
$subject
fixes #939 
Test template output:
```xml
<network ipv6='yes'>
<name>linchpin-centos74</name>
/>
<forward mode="nat"/>
<domain name="linchpin.net" localOnly="yes"/>
<ip address="192.168.74.100"  netmask="255.255.255.0" >
<dhcp>
<range start="192.168.74.101" end="192.168.74.112"/>
</dhcp>
</ip>
</network>
```
> Updated schema, template to support netmask in libvirt network provisioning

- linchpin/provision/roles/libvirt/files/schema.json
- linchpin/provision/roles/libvirt/templates/libvirt_network.xml.j2
- do not require the ip attribute to be set
- do not required forward mode attribute to be set
Fixes #969
> Allow creating bridge libvirt networks

- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
- linchpin/provision/roles/libvirt/templates/libvirt_node.xml.j2
This change implements the following changes that allow creating multiple
libvirt VMs with multiple disks attached to each:
- create disks via qemu-img for each VM
- create disks via qemu-img for each item in the storage attribute
- change the disk file name to reflect the qcow2 format
- correct typo in the target tag in libvirt_node.xml.j2
Fixes #974
> Allow attaching multiple disks to multiple libvirt VMs

- config/s2i/jenkins/master/configuration/jobs/ci-linchpin-messageBus-merge/config.xml
- config/s2i/jenkins/master/configuration/jobs/ci-linchpin-messageBus-trigger/config.xml
- config/s2i/jenkins/master/plugins.txt
jms-messaging-1.1.5 fixes a bug where Jenkins restarts removed the fedmsg override topic from the triggers
Signed-off-by: Johnny Bieren <jbieren@redhat.com>
> Upgrade to JMS Messaging 1.1.5

- docs/source/examples/workspaces/libvirt-no-dhcp/PinFile
- linchpin/provision/roles/libvirt/files/schema.json
- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
The new option allows user to decide if node's network should provide IP automatically and Linchpin will wait for that to happen. Otherwise linchpin will skip that network. If there is no network with DHCP enabled, the inventory will be empty.
Fixes #980
> Libvirt optional DHCP for node network

- docs/source/cli.rst
- docs/source/includes/setup.rst
- docs/source/linchpin_setup.rst
- linchpin/shell/__init__.py
- linchpin/shell/click_default_group.py
- Fixed the help text on `linchpin setup --help`
- Added 'setup' on list of commands of cli documentation, and
make a page for it.
- Show 'setup' on the list of commands when `linchpin --help`
> cli: improve the setup subcommand documentation

- linchpin/utils/dataparser.py
We load templates as an OrderedDict, which Ansible cannot parse in its template rendering.  Until Ansible can, which should be shortly after it stops supporting python 2.6, we can revert this change
> Prevent dicts in template from being treated as strings

- docs/source/installation.rst
The blocks of code were malformatted. Instead of just fix,
refactored the section.
> docs: refactor setup section on installation page

- config/Dockerfiles/Jenkinsfile
- config/Dockerfiles/JenkinsfileContainer
- config/Dockerfiles/JenkinsfileGHPRMerge
- config/Dockerfiles/JenkinsfileGHPRTrigger
- config/Dockerfiles/JenkinsfileMergePR
- config/Dockerfiles/JenkinsfileMessageBusMerge
- config/Dockerfiles/JenkinsfileMessageBusTrigger
- config/Dockerfiles/JenkinsfileRelease
- config/s2i/jenkins/master-downstream/configuration/jobs/cd-linchpin-release/config.xml
- config/s2i/jenkins/master-downstream/configuration/jobs/ci-linchpin-container/config.xml
- config/s2i/jenkins/master-downstream/configuration/jobs/ci-linchpin-merge/config.xml
- config/s2i/jenkins/master-upstream/configuration/jobs/cd-linchpin-release/config.xml
- config/s2i/jenkins/master-upstream/configuration/jobs/ci-linchpin-GHPRB-merge/config.xml
- config/s2i/jenkins/master-upstream/configuration/jobs/ci-linchpin-GHPRB-trigger/config.xml
- config/s2i/jenkins/master-upstream/configuration/jobs/ci-linchpin-container/config.xml
- config/s2i/jenkins/master-upstream/configuration/jobs/ci-linchpin-merge/config.xml
This will allow multiple branches to be in development at the
same time.  Containers promoted to stable from one branch will
not affect another branch.
This PR is dependent on https://github.com/CentOS-PaaS-SIG/ci-pipeline/pull/793
> Support stable tags based on the branch

- linchpin/provision/roles/libvirt/files/schema.json
- linchpin/provision/roles/libvirt/tasks/copy_image_src_local.yml
- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
- linchpin/provision/roles/libvirt/tasks/teardown_libvirt_node.yml
- linchpin/provision/roles/libvirt/templates/cloud-config/meta-data
- linchpin/provision/roles/libvirt/templates/libvirt_node.xml.j2
This change allows creating VMs with a custom separator between the
name and index, e.g:
$name-$index; currently only $name_$index is possible
Fixes #985
> Introduce name_separator attribute for libvirt resource

- docs/source/examples/workspaces/libvirt/PinFile
- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
Fixes #1023  - When a  libvirt system has multiple networks and has a subset with disabled dhcp, it will falsely to get a mac of skipped network, ending up in missing item (non existing dictionary path). The simple solution is to filter the valid networks for mac gathering before looking for mac addresses.
> fix libvirt waiting for IP on net with disabled dhcp

- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
This change adjusts the OpenStack instances naming so that:
- index starts at 0 instead of 1
- there is a '-' separator between the resource name and index
This makes the naming consistent with the libvirt provider.
> Adjust OpenStack instance naming

- linchpin/provision/roles/openstack/tasks/provision_os_router.yml
Currently removing an os_network that is connected to a router fails
with "Unable to complete operation on network. There are one or more
ports still in use on the network." This change sets the router interfaces
to an empty list during destroy hence allowing the router and
subsequent os_network delete to complete.
Failure:
```yaml
PLAY [schema check and Pre-Provisioning Activities on topology_file] ***********
TASK [common : assign async value] *********************************************
ok: [localhost] => {"ansible_facts": {"async": false}, "changed": false}
TASK [common : declare async_types array] **************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}
TASK [common : output vars] …
```
> Allow removing OpenStack routers with connected networks during destroy

- config/Dockerfiles/JenkinsfileRelease
Syntax fixes for release job to work.
Don't push all tags, just push the new tag.
Comment out buildah steps for now since we don't have the command
in the container.
> Fixes to release job

- linchpin/provision/roles/libvirt/files/schema.json
- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
- linchpin/provision/roles/libvirt/templates/libvirt_node.xml.j2
Use host-model as default and make it configurable via cpu_mode parameter.
> Allow passing cpu mode to libvirt VM

- config/Dockerfiles/JenkinsfileGHPRMerge
- config/Dockerfiles/JenkinsfileMessageBusMerge
Downstream wasn't getting the ghprbGhRepository populated
because it wasn't included in the messagebus message.
> Add missing ghprbGhRepository variable for downstream

- linchpin/InventoryFilters/GenericInventory.py
Inventory fails when os_keypair and os_server are provisioned together. 
```
---
os-server-addl-vols:
topology:
topology_name: os-server-inst
- resource_group_name: os-server-test-lp
resource_group_type: openstack
- name: linchpintestkey
role: os_keypair
- name: "linchpintestdatabase"
role: os_server
flavor: m1.small
image: CentOS-7-x86_64-GenericCloud-1808
count: 1
keypair: linchpintestkey
networks:
- provider_net_cci_6
credentials:
filename: clouds.yaml
profile: openstack
layout:
inventory_layout:
vars:
hostname: __IP__
hosts:
addl-vols-node:
count: 1
host_groups:
- hello
```
Error while debugging with PDB
```
17             """
18             host_data = []
19             for res_grp in res_output:
20                 inv_filter = …
```
> bugfix: get inventory data only when inv_filter is defined

- docs/source/examples/workspaces/openstack/PinFile
$subject 
Since floating ips are no longer used in psi infra
changes to make tests pass.
> Remove fip_pool parameter from examples

- .travis.yml
Though this pr does not intend to replace contra.yml. 
It helps in triggering unit tests manually from travis ui.
> Add travis.yml to manually trigger unit tests

- config/Dockerfiles/JenkinsfileContainer
- config/Dockerfiles/JenkinsfileRelease
- config/s2i/jenkins/buildah/Dockerfile
There's a couple of other references to copr repos that will be a bit harder to remove that we can get to another time
> Remove herlo from JenkinsFiles

- config/Dockerfiles/tests.d/general/01_general
- playbooks/tests/unit_tests.yml
Will be reverting it back once the container is fixed. until then, please
refer to Travis ci logs for tests
> Disabling unit tests in linchpin via contra hdsl

- config/Dockerfiles/JenkinsfileRelease
This PR fixes the following error in linchpin release 
```
Started by upstream project "ci-linchpin-GHPRB-merge" build number 302
originally caused by:
GitHub pull request #1060 of commit ae0653a00acbe033fd39957d8913f0e9c2a9a3bc, no merge conflicts.
Obtained config/Dockerfiles/JenkinsfileRelease from git https://github.com/CentOS-PaaS-SIG/linchpin
Running in Durability level: MAX_SURVIVABILITY
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 220: expecting '}', found 'version' @ line 220, column 36.
string version = sh (
^
1 error
at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:150)
at …
```
> bugfix: Fix linchpin release compilation error

- config/Dockerfiles/JenkinsfileRelease
We were passing "1.7.4" to the script, while the release was tagged as "v1.7.4"
> Fix bug preventing releases from being created

- config/Dockerfiles/JenkinsfileContainer
Disable openstack cleanup since it is holding up the release. We can re-enable it in a future PR
> Disable Openstack Cleanup

- linchpin/FilterUtils/FilterUtils.py
- linchpin/provision/roles/openstack/files/schema.json
- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
- linchpin/tests/InventoryFilters/test_FilterPlugins_pass.py
* Issue 1137 - Update the 'additional_volumes' key in the
openstack schema.json to be compatible with Cerberus 1.3.1
* Issue 1139 - Moved up the two 'generate res_def_names' tasks in
the provision_os_server.yml to occur before the additional_volumes
processing. Also updated the 'render_os_server_insts' filter to
remove the server_name creation logic and use the res_def_names instead
* Updated the test 'test_os_server_insts'
> Fixes for OpenStack 'additional_volumes'

- config/Dockerfiles/tests.d/aws/06_aws_ec2_elb_lb
- config/Dockerfiles/tests.d/openstack/06_os-heat
- docs/source/examples/workspaces/aws/PinFile
- docs/source/examples/workspaces/openstack-heat/PinFile
- docs/source/examples/workspaces/openstack/PinFile
- linchpin/InventoryFilters/AWSInventory.py
- linchpin/InventoryFilters/BeakerInventory.py
- linchpin/InventoryFilters/DockerInventory.py
- linchpin/InventoryFilters/DuffyInventory.py
- linchpin/InventoryFilters/DummyInventory.py
- linchpin/InventoryFilters/GCloudInventory.py
- linchpin/InventoryFilters/InventoryFilter.py
- linchpin/InventoryFilters/LibvirtInventory.py
- linchpin/InventoryFilters/OpenstackInventory.py
- linchpin/InventoryFilters/OvirtInventory.py
- linchpin/tests/InventoryFilters/test_AWSInventory_pass.py
- linchpin/tests/InventoryFilters/test_BeakerInventory_pass.py
- linchpin/tests/InventoryFilters/test_DuffyInventory_pass.py
- linchpin/tests/InventoryFilters/test_DummyInventory_pass.py
- linchpin/tests/InventoryFilters/test_GCloudInventory_pass.py
- linchpin/tests/InventoryFilters/test_LibvirtInventory_pass.py
- linchpin/tests/InventoryFilters/test_OpenstackInventory_pass.py
- linchpin/tests/InventoryFilters/test_OvirtInventory_pass.py
- linchpin/tests/InventoryFilters/test_VMwareInventory_pass.py
Many of the provider-specific inventory filter functions are never used (and likely never will be) so there's no need to keep them around
> Remove unused functions from Inventory Filters

- linchpin/FilterUtils/FilterUtils.py
- linchpin/provision/filter_plugins/fetch_beaker_job_ids.py
- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
- linchpin/tests/InventoryFilters/test_FilterPlugins_pass.py
fixes #1153 
Summary:
- added fetch_beaker_ids filter
- added unit test to fetch_beaker_ids
- Updated playbooks to handle timed out beaker resources
> Cancel beaker job when there is a timeout while fetching the resources

- docs/source/examples/workspace/linchpin.conf
- linchpin/linchpin.constants
- linchpin/provision/roles/gather_resources/tasks/wait.yml
- linchpin/provision/roles/gather_resources/tasks/wait_on_aws_ec2.yml
- linchpin/provision/roles/gather_resources/tasks/wait_on_gcloud_gce.yml
- linchpin/provision/roles/gather_resources/tasks/wait_on_os_heat.yml
- linchpin/provision/roles/gather_resources/tasks/wait_on_os_obj.yml
- linchpin/provision/roles/gather_resources/tasks/wait_on_os_server.yml
- linchpin/provision/roles/gather_resources/tasks/wait_on_os_volume.yml
- linchpin/provision/roles/gather_resources/tasks/wait_on_vmware_guest.yml
fixes #1148
Summary:
- adds async_retries option to configure the number of retries
- updated example linchpin.conf
- updated playbooks
> Add support for async_retries option in linchpin

- linchpin/ansible_runner.py
Fixes : #1180 
import context is available only on ansible 2.8 or higher. 
the following PR introduces a conditional import based on ansible version
> bugfix to ansible_runner to maintain backward compatibility

- requirements.txt
Duplicate requirements found on requirements.txt causing error on linchpin release
```
00:26:16  DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
00:26:16  ERROR: Double requirement given: urllib3<1.25 (from -r /tmp/tmp.wpSCcliKzL/requirements.txt (line 23)) (already in urllib3<1.25,>=1.23 (from -r /tmp/tmp.wpSCcliKzL/requirements.txt (line 16)), name='urllib3')
00:26:16  + pip install linchpin==1.7.6 --index-url https://test.pypi.org/simple
00:26:16  DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip …
```
> remove duplicate requirements.txt

- .travis.yml
- linchpin/InventoryFilters/AWSInventory.py
- linchpin/InventoryFilters/BeakerInventory.py
- linchpin/InventoryFilters/DockerInventory.py
- linchpin/InventoryFilters/DuffyInventory.py
- linchpin/InventoryFilters/DummyInventory.py
- linchpin/InventoryFilters/GCloudInventory.py
- linchpin/InventoryFilters/LibvirtInventory.py
- linchpin/InventoryFilters/OpenstackInventory.py
- linchpin/InventoryFilters/OvirtInventory.py
- linchpin/InventoryFilters/VMwareInventory.py
- linchpin/tests/InventoryFilters/test_GenericInventory_pass.py
- linchpin/tests/mockdata/complex-inventory/correct-inventory
There were two failing tests: The first failed because the hosts within a host group were listed in different orders.  This was resolved by switching the inventory formatters to OrderedDicts instead of dicts.  The second was the test that verified the order of the generated inventory file as a whole, which failed because the host groups were consistently being printed in different orders.  Seeing as this test is not necessary and the failure seems to be the result of the configparser module, this test was removed.
> Fix bugs causing unit tests to fail in python 3

- requirements.txt
GitPython 2.1.12 is only compatible with Python 3.  This freezes the version at 2.1.11 until Python 2 support is dropped
> Freeze GitPython version

- config/Dockerfiles/tests.d/libvirt/02_libvirt-storage
- config/Dockerfiles/tests.d/libvirt/05_libvirt-builtins
Temporarily disable all the libvirt tests since we are blocked on resolving SELinux issues
> disable all the libvirt based tests

- requirements.txt
As a bug fix to issue #1269 
including future package inside for supporting rhel images
> add "future" package to requirements

- config/Dockerfiles/tests.d/dummy/10_dummy-use-shell
- config/Dockerfiles/tests.d/inventory/02_json_inventory
- docs/source/includes/cli_basic_usage.rst
- docs/source/includes/provisioning.rst
- linchpin/__init__.py
- linchpin/ansible_runner.py
- linchpin/cli/__init__.py
- linchpin/context.py
- linchpin/hooks/__init__.py
- linchpin/hooks/action_managers/ansible_action_manager.py
- linchpin/linchpin.constants
- linchpin/shell/__init__.py
Fixes #1125 
This is a preview feature which enables running of ansible_runner as subprocess shell
instead of running ansible API. 
example usage:
```
linchpin -vvvvv up --use-shell --env-vars TESTENV envvalue
```
> Enable passing environment vars and run ansible_runner as subprocess

- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
Currently the private key gets appended to ~/.ssh/authorized_keys which is wrong. This change adjusts the tasks so they append the public key to ~/.ssh/authorized_keys.
Fixes: https://github.com/CentOS-PaaS-SIG/linchpin/issues/1290
> Append public key to ~/.ssh/authorized_keys in libvirt provider

- docs/source/examples/workspaces/openstack-net/PinFile
- docs/source/examples/workspaces/openstack-net/README.md
- docs/source/examples/workspaces/openstack-net/linchpin.conf
- linchpin/provision/roles/openstack/files/schema.json
- linchpin/provision/roles/openstack/tasks/main.yml
- linchpin/provision/roles/openstack/tasks/provision_os_network.yml
- linchpin/provision/roles/openstack/tasks/provision_os_router.yml
- linchpin/provision/roles/openstack/tasks/provision_os_subnet.yml
- linchpin/provision/roles/openstack/tasks/teardown_os_heat.yml
- linchpin/provision/roles/openstack/tasks/teardown_os_keypair.yml
- linchpin/provision/roles/openstack/tasks/teardown_os_network.yml
- linchpin/provision/roles/openstack/tasks/teardown_os_object.yml
- linchpin/provision/roles/openstack/tasks/teardown_os_router.yml
- linchpin/provision/roles/openstack/tasks/teardown_os_server.yml
- linchpin/provision/roles/openstack/tasks/teardown_os_sg.yml
- linchpin/provision/roles/openstack/tasks/teardown_os_subnet.yml
- linchpin/provision/roles/openstack/tasks/teardown_os_volume.yml
- linchpin/provision/roles/openstack/tasks/teardown_resource_group.yml
- Openstack teardown of network resources wasn't in specific order which failed when there is dependency (net -> sub -> router).
- Network resources names were generated (uhash) which makes it impossible to link dependent resources (net -> sub -> router)f
> Fix Openstack Network managment

- config/Dockerfiles/tests.d/azure/02_azure_virtual_network
- docs/source/azure.rst
- linchpin/provision/roles/azure/files/schema.json
- linchpin/provision/roles/azure/tasks/main.yml
- linchpin/provision/roles/azure/tasks/provision_azure_virtual_network.yml
- linchpin/provision/roles/azure/tasks/provision_res_defs.yml
- linchpin/provision/roles/azure/tasks/teardown_azure_virtual_network.yml
- linchpin/provision/roles/azure/tasks/teardown_res_defs.yml
- linchpin/provision/roles/azure/tasks/teardown_resource_group.yml
- linchpin/provision/roles/gather_resources/tasks/main.yml
Added virtual network creation and destruction
> Azure virtual network

- config/Dockerfiles/tests.d/azure/04_azure_vm_public_image
- docs/source/azure.rst
- docs/source/examples/workspaces/azure/PinFile
- linchpin/provision/roles/azure/files/schema.json
- linchpin/provision/roles/azure/tasks/provision_azure_vm.yml
Enabled public image for Linchpin Azure
For current Azure support, we only support private image which means you can only create vm based on the user owned images. After enable the public image, user could create vm based on any online image
> Enable public image azure

- linchpin/provision/roles/openstack/tasks/provision_os_server.yml
Remove missing filter which is causing the failure in openstack instances deletion
> fix openstack teardown bug remove missing filter

- config/Dockerfiles/centos7/Dockerfile
This will allow the `linchpin-nightly` pipeline to clean up the instances
> Make container image changes necessary to run openstack cleanup nightly

- linchpin/provision/roles/dependencies/tasks/libvirt_deps.yml
Move python2-dnf depedency from yum/dnf to pip since the package no
longer exists in fedora 30
Fixes #1340
> Move python2-dnf dependency to pip

- .gitignore
This just prevents people from accidentally uploading credentials when they submit a PR
> Ignore credentials in workspaces

- docs/source/examples/workspaces/aws-simple/PinFile
- docs/source/examples/workspaces/aws/PinFile
- docs/source/examples/workspaces/dummy-aws/PinFile.dummy-aws.yml
Update the default (or in some cases hard-coded) values for aws_ec2
resources to be compatible with our new ec2 region.  This will also fix the last failure in #1287
> Update aws ec2 examples to reflect changes in account

- linchpin/ansible_runner.py
Linchpin  --use-shell feature does not work on python3.7 environments
The following commit acts as a fix for the same.
> Python3 fix for --use-shell flag

- docs/source/azure.rst
- docs/source/providers.rst
Add the examples by changing name of Providers, the name "Examples for Proveders" make more sense for user to find the examples fix #1199
> Added Azure doc and change name "Provediers" to Examples

- linchpin/ansible_runner.py
Since in requirements.txt we support only ansible versions>=2.7.1. 
The following PR cleans up ansible runner code dropping support for ansible versions
2.6.x or below
> Drop support for ansible 2.6.x or below

- docs/source/installation.rst
Virtual Environments and SELinux: The first sentence had 'to' and 'with', removed with.
> Virtual Environments and SELinux: Removed word 'with'

- docs/source/workflow.rst
Fetching a remote workspace- I dont think Fetch is correct though it is used in the following code.
Contents of a workspace-both was removed as there is only one option-Git Repo 
-'have should' was replaced with 'should have'
> Grammar changes

- docs/source/examples/workspaces/dummy-python-hook/PinFile
- docs/source/examples/workspaces/dummy-python-hook/hooks/python/ex_hook/find_pinfile.py
- docs/source/examples/workspaces/dummy-python-hook/hooks/python/ex_hook/list_files.py
- docs/source/hooks.rst
- linchpin/__init__.py
- linchpin/hooks/__init__.py
- linchpin/hooks/action_managers/nodejs_action_manager.py
- linchpin/hooks/action_managers/python_action_manager.py
- linchpin/hooks/action_managers/ruby_action_manager.py
- linchpin/hooks/action_managers/subprocess_action_manager.py
- linchpin/provision/module_utils/linchpin_rundb.py
Improve the manner in which data is passed between hooks.  Since this feature is targeted for 2.0, this is experimental for now.  In particular, `-destroy` hooks cannot collect data from `-up` hooks.  This is something I'm still working on but I wanted to get this piece submitted
> Improve hook communication

- docs/source/providers.rst
Missed Azure for the linchpin documentation
> Added Azure to examples(providers)

- config/Dockerfiles/tests.d/azure/03_azure_virtual_subnet
- config/Dockerfiles/tests.d/azure/04_azure_vm_public_image
- linchpin/InventoryFilters/GenericInventory.py
- linchpin/__init__.py
- linchpin/galaxy_runner.py
- linchpin/tests/InventoryFilters/test_GenericInventory_pass.py
- linchpin/tests/validator/test_init_pass.py
- linchpin/validator/__init__.py
Currently linchpin only looks in ~/.ansible/roles.  This expands the search area to all directories listed in `ansible-galaxy list`
Fixes #1408
> Make linchpin look in multiple locations for ansible galaxy roles

- requirements.txt
Due to the recent changes in infrastructure, 
ansible no longer works with latest versions of OpenStack SDK 
Until the issue is fixed we are going to restrict version of openstacksdk to 0.26
fixes: #1427  for the time being
> restrict version of openstacksdk to 0.26

- linchpin/provision/roles/common/tasks/main.yml
- linchpin/provision/roles/gather_resources/tasks/main.yml
This allows role developers to avoid the hard-coding in gather_resources while developing external roles
> Allow roles to write to topology_outputs directly

- linchpin/galaxy_runner.py
testing develop branch with Carbon and The following errors are observed
```
Traceback (most recent call last):
File "/home/jenkins/workspace/e2e-openstack-linchpin-2/cbn/lib/python2.7/site-packages/blaster/engine/parallel.py", line 45, in run
task_obj = task_cls(**task_def)
File "/home/jenkins/workspace/e2e-openstack-linchpin-2/cbn/lib/python2.7/site-packages/carbon/tasks/provision.py", line 53, in __init__
plugin = getattr(asset, 'provisioner_plugin')(asset)
File "/home/jenkins/workspace/e2e-openstack-linchpin-2/cbn/lib/python2.7/site-packages/carbon/provisioners/ext/linchpin_wrapper_plugin.py", line 72, in __init__
self.linchpin_api = LinchpinAPI(self._init_context())
File "/home/jenkins/workspace/e2e-openstack-linchpin-2/cbn/lib/python2.7/site-packages/linchpin/__init__.py", line 92, …
```
> Update galaxy_runner get_role_paths function

- linchpin/galaxy_runner.py
This is the less hacky (but potentially less stable) way of finding the role paths that Ansible uses
> Use the ansible galaxy python API to search for role paths

- docs/source/examples/workspaces/openstack-heat/os_stack.yml
Need to update heat examples to make it. 
HOT templates are expected to specify the tags parameter.
> Updated example for os-heat to make downstream tests pass.

- requirements.txt
Update OpenStack SDK to version 37 to see if the openstack server provisioning bug 
was fixed.
> Update openstacksdk to 37

- linchpin/context.py
* check for handlers before configuring lp_console logger
in case other applications use linchpin like a library
and have configured the logger for linchpin.
Fixes:#1475
> Modified LinchpinContext setup_logging

- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
Instead of wasting 2 minutes waiting let's run sync to write the memory data to disk, which should avoid failures caused by delayed write locks.
> Run sync instead of sleep during libvirt provisioning

- linchpin/ansible_runner.py
- linchpin/rundb/mongodb.py
Fixes #1504 
Ansible does not allow imports which are nonexistent in the python environment within module_utils
and causes JSON error as a side effect since module_utils are not loaded. 
The above fix is a hack for #1504 
I could not find any better solution at this point in time. 
Note:
Further, one should have a clean installation of linchpin. 
Since if we try installing linchpin again in existing virtualenv it wont work. 
existing linchpin should be uninstalled using 
```
pip3 uninstall linchpin
```
@Dannyb48 Let me know if it works
@abraverm  ^^^ this should work with both python3 and python2 envs
> Suppress pymongo imports inside module_utils

- linchpin/provision/roles/dependencies/tasks/beaker_deps.yml
- linchpin/provision/roles/dependencies/tasks/main.yml
- setup.py
Install beaker dependencies from beaker repo
> Update beaker setup dependencies with linchpin

- linchpin/ansible_runner.py
- linchpin/hooks/__init__.py
Also, all ansible commands were running as shell commands because of a configuration issue.  This fixes that error as well
> Make ansible hooks use proper verbosity

- scripts/install_selinux_venv.sh
On RHEL8 _selinux.so file is not present. This change adjusts the symlinks in install_selinux_venv.sh to match python version present on RHEL8.
> Fix install_selinux_venv.sh for RHEL8 environments

- readthedocs.yml
$subject 
The recent updates in readthedoc environment needs sphinx-automodapi
to be added to the requirements.txt to pass builds. 
refer: 
https://readthedocs.org/projects/linchpin/builds/10204633/
> add readthedocs config yaml file to linchpin

- docs/source/examples/workspace/linchpin.conf
- linchpin/api/__init__.py
- linchpin/linchpin.constants
- linchpin/provision/roles/aws/tasks/provision_resource_group.yml
- linchpin/provision/roles/aws/tasks/teardown_resource_group.yml
- linchpin/provision/roles/azure/tasks/provision_resource_group.yml
- linchpin/provision/roles/azure/tasks/teardown_resource_group.yml
- linchpin/provision/roles/gcloud/tasks/provision_resource_group.yml
- linchpin/provision/roles/nummy/tasks/provision_resource_group.yml
- linchpin/provision/roles/openshift/tasks/provision_resource_group.yml
- linchpin/provision/roles/openstack/tasks/provision_resource_group.yml
- linchpin/provision/roles/ovirt/tasks/provision_resource_group.yml
- linchpin/provision/roles/rackspace/tasks/provision_resource_group.yml
- linchpin/provision/roles/vmware/tasks/provision_resource_group.yml
Debug mode is required for CI investigation (for linchpin project or user tests) and it could be needed by CI engineers (infra owners) or CI users (Quality engineers), but not everyone should able to see authentication credentials in that case. The change adds a new variable to Linchpin config to separate between general debug mode and credentials specific case.
> Auth debug variable

- linchpin/provision/roles/beaker/tasks/provision_resource_group.yml
The resource group type was being read as an AnsibleUnsafeText, which was preventing the res data from being formatted correctly. This makes the resource group type a string
Resolves #1561
> Fix error with beaker res data

- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
- linchpin/provision/roles/libvirt/templates/libvirt_node.xml.j2
Avoid unnecessary creation of directories when cloud_config is not de…clared
Further, this PR looks into the problem of provisioning instances without cloud_config. 
Bug description:
when provisioning a libvirt-cirros workspace 
linchpin hangs up 
Steps to reproduce:
```
linchpin init libvirt-cirros
linchpin -vvvv up 
```
Actual behavior:
1. linchpin hangs up while provisioning cirros image 
expected:
linchpin provisions cirros image.
> Avoid unnecessary creation of directories when not using cloud_config

- docs/source/credentials/libvirt.rst
- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
Re-running provisioning as non-root user fails:
``` yaml
TASK [libvirt : localhost: Generate ci data cd image for cloud-init when cloud config is defined] ***
failed: [localhost] (item=['master', 0, '-']) => {"ansible_loop_var": "definition", "changed": true, "cmd": ["mkisofs", "-o", "/tmp/vm-master-0.iso", "-V", "cidata", "-r", "-J", "--quiet", "/tmp/vm-master-0/user-data", "/tmp/vm-master-0/meta-data"], "definition": ["master", 0, "-"], "delta": "0:00:00.003242", "end": "2020-01-28 16:54:42.858604", "msg": "non-zero return code", "rc": 13, "start": "2020-01-28 16:54:42.855362", "stderr": "genisoimage: Permission denied. Unable to open disc image file '/tmp/vm-master-0.iso'.", "stderr_lines": ["genisoimage: Permission denied. Unable to open disc image file '/tmp/vm-master-0.iso'."], …
```
> Specify file-mode for output file.

- docs/source/examples/workspaces/azure/PinFile
The hook is causing all PRs that test azure to fail.  Disabling until #1600 is resolved
> Temporarily disable postup hook for azure_vm

- linchpin/provision/roles/aws/tasks/teardown_resource_group.yml
AWS EC2 destroy is currently fails due to the rundb output being a string .
This PR uses the convert_to_json filter to load the topology out from string if it is a string else it returns the same.
> load strings from topology output to fix AWS EC2 destroy

- linchpin/provision/roles/gather_resources/tasks/main.yml
I noticed this while I was working on something else.  #1607 didn't aggregate outputs into `topology_outputs`, it overwrote the outputs every time.  This fixes that bug
> Fix bug preventing topology outputs from multiple sources from being collected

- docs/source/examples/workspaces/libvirt/custom.xml
- linchpin/provision/roles/libvirt/files/schema.json
- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
fixes #1228 
Fixes a couple of bugs with libvirt provisioning with cloud-init config.
1. Provisioning with cloud-config 
2. Remote provisioning  
Further, linchpin currently provisions successfully when we use linchpin-custom-xml topology. 
This PR also introduces remote_python_interpretor schema key resolve differences between python_interpretor of linchpin machine and remote_libvirt_host. 
Note:
As long as there is a ssh connection setup between both client machine and remote_libvirt_host, linchpin provisions libvirt instances. 
This does not work when the linchpin machine is running in a virtual machine.
> Fix remote provisioning of libvirt accross environments (except virtualenvs)

- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
Syntax error in https://github.com/CentOS-PaaS-SIG/linchpin/pull/1620
Signed-off-by: Johnny Bieren <jbieren@redhat.com>
> Remove extra }}

- linchpin/provision/roles/aws/molecule/delegated/create.yml
- linchpin/provision/roles/aws/molecule/delegated/destroy.yml
- linchpin/provision/roles/aws/molecule/delegated/molecule.yml
- linchpin/provision/roles/aws/molecule/delegated/tests/test_null.py
- linchpin/provision/roles/aws/molecule/shared/playbook.yml
Adds support for the delegated driver in molecule tests that that we don't have to use nested containers in github actions
To run the delegated driver locally, you may have to set `ansible_python_interpreter` to the python interpreter within your virtual environment.  This is set under `ansible_connection_options` in `molecule/delegated/molecule.yml`
> Add delegated driver support to molecule tests

- .github/install_dependencies.sh
- .github/runmocktests.sh
- .github/workflows/linting.yml
- .github/workflows/multicontainertesting.yml
- docs/source/examples/workspaces/dummy-python-hook/hooks/python/ex_hook/find_pinfile.py
- linchpin/tests/test_init_pass.py
The following PR uses GitHub actions to run all the CI related testing on
Centos7,8 and fedora 30,31,32 
To be merged after #1625 
fixes: #1626
> POC: Run CI testing using github actions

- linchpin/provision/action_plugins/ec2.py
This should fix a zmq hang I was having in Carbon when provisioning ec2 resources even though I had setup no_monitor evar and context keys.
> Fixes an EC2 provisioning zmq hang

- linchpin/validator/__init__.py
Fixes #1578 where validate_pretty was not returning a non zero return code if the layout or cfg of the schema was failed to validate.
> Fix validation return codes

- .github/run_aws_mocktests.sh
- .github/run_beaker_mocktests.sh
- .github/run_gcloud_mocktests.sh
- .github/run_openstack_mocktests.sh
- .github/workflows/multicontainertesting.yml
- linchpin/provision/action_plugins/ec2.py
In order to easily verify the logs we have to breakdown GitHub actions into multiple steps 
Further, a couple of tests were failing for aws-ec2 due to a bug on ec2.py action_plugin 
and also the mock data was missing. 
The following PR fixes the above situation.
> Fix bug with aws ec2 mock & Breakdown GitHub actions into multiple steps 

- linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml
- linchpin/provision/roles/libvirt/templates/libvirt_node.xml.j2
$subject
#1630 
@johnbieren Please check if this patch works for you.
> update logic for cloud-init and variable names for resolving ambiguity

- linchpin/provision/roles/libvirt/tasks/copy_image_src_remote.yml
Task `Add additional storage` in `libvirt/tasks/provision_libvirt_node.yml` uses `res_def['name_separator']` when composing path for **qemu-img resize** command
```yaml
- name: "Add additional storage"
command: "qemu-img resize {{ definition[1] }}/{{ definition[0] }}{{ definition[5] }}{{ definition[4] }}.{{ definition[2] }} +{{ definition[3] }}"
with_nested:
- ["{{ libvirt_resource_name }}"]
- ["{{ libvirt_image_path | expanduser }}"]
- ["{{ img_src_ext }}"]
- ["{{ res_def['additional_storage'] }}"]
- "{{ res_count }}"
- ["{{ res_def['name_separator'] }}"]
loop_control:
loop_var: definition
become: "{{ libvirt_become }}"
remote_user: "{{ res_def['remote_user'] }}"
```
But in `copy_image_src_remote.yml` it's hardcoded to `_` causing task to fail
> Don't hardcode name_separator for remote task

- linchpin/FilterUtils/FilterUtils.py
- linchpin/tests/InventoryFilters/test_FilterPlugins_pass.py
This should fix #1693 where two resources belong to the same
job are filtered to avoid xmlrpc condition
> Fix an xmlrpc beaker error when count > 1

- .github/workflows/packaging.yml
- linchpin/provision/linchpin.yml
Linchpin RPM was failing on Beaker module import, and we found out by customer who tried to provision with it.  The import issue was fixed in RPM build PR, this PR adds RPM testing for Beaker. During test development, I found another bug - Linchpin fails to run on systems without SSH, the PR fixes that too.
> Test Beaker with Linchpin RPM

- linchpin/hooks/__init__.py
- linchpin/hooks/action_managers/ansible_action_manager.py
- linchpin/tests/hooks/action_managers/test_ansible_action_manager.py
* Fix #1709 where no_monitor was not being propagated to the
ansible action manager to disable the zmq multiprocess/progress bar code
* Fix an issue with the dummy action plugin causes hangs as well
> Fix ansible hooks hanging

- .github/workflows/autobump.yml
- .github/workflows/publishtopypi.yml
Contains GitHub workflows that enable the following:
- Autobumps the version and tags the branches 
- Publish to PyPI based on the version changes
fixes #1633
> Add workflows to make PYPI releases
